### PR TITLE
Added stream correlation notebook

### PR DESCRIPTION
**Pull request by MatthewJA**
Added a notebook that estimates the correlation between TCW in each pixel and nearby stream gauges. BOM Water Data Online is being super patchy right now so when I run it it only gives data for one of the two example stream gauges, but the notebook still works.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
I'll have a closer look at this a little later on - for now, it would be good to update the introductory markdown to closer match the other real-world notebooks. For these ones we've tried to include the following three headers where possible, so that they can be used as part of DEA workshops and tutorials for beginners or non-technical users (`Frequently_used_code` notebooks are often a bit more relaxed and just include the single compulsory Description section):

1. Background: general overview of the ecological/environmental/management problem (not specific to DEA)
2. DEA/satellite data use case: how DEA and/or satellite data can help to address this problem
3. Description: A technical description of what exactly this notebook does

I think you have a lot of that content in there, just needs to be broken up a bit and elaborated on so that users can be taken on that journey of "yeah, that does sound like a tricky problem" > "I see how DEA/satellite data could potentially help solve that" > "I see exactly how we're going to solve that".

There's some nice examples here:

- https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/Real_world_examples/Mining_rehabilitation.ipynb
- https://docs.dea.ga.gov.au/notebooks/Real_world_examples/Radar_water_detection.html
- https://docs.dea.ga.gov.au/notebooks/Real_world_examples/Coastal_erosion.html


I'd also replace the current "Stream gauge/pixel correlations" title with something a bit more descriptive like "Calculating pixel correlations with stream gauge data" or similar

**Comment by robbibt** [comment]
Also possibly worth drawing your attention to two other ancient notebooks that deal with similar workflows, but were never migrated from the `master_archive` branch:

* Per pixel regression of tide heights: https://github.com/GeoscienceAustralia/dea-notebooks/blob/master_archive/05_Temporal_analysis/PerPixelRegression.ipynb
* Per pixel regression for groundwater: https://github.com/GeoscienceAustralia/dea-notebooks/blob/master_archive/09_Workflows/LinearModels-NDVI_recession.ipynb

Both of them were based on the [`lag_linregress_3d` function](https://stackoverflow.com/a/52711081/2510900) that calculates lots of per-pixel regression params in a nice and quick vectorised way (have always wanted to migrate a version of that func over to `Scripts`). Might be some things that could be harvested and integrated here?

**Comment by MatthewJA** [comment]
I'll port that `lag_linregress_3d` function over!

**Comment by MatthewJA** [comment]
I may also have autoformatted `dea_temporal`...

**Review by robbibt — CHANGES_REQUESTED** [review]
Hey @MatthewJA , looks like there's a new conflict here with `dea_temporal.py`, might have been caused by some of the DEA tools updates?

There's also an error in the current version of the notebook that would be good to fix before we merge:
image

**Comment by MatthewJA** [comment]
Did you get that error running it just now? If so, that's the BOM API failing.

I can fix the temporal issue though, will do shortly :)

**Comment by robbibt** [comment]
That error is in the currently committed version of the notebook; just want to get a clean run stored in git so the error doesn't get rendered in the docs!

e.g. here: https://github.com/GeoscienceAustralia/dea-notebooks/blob/MatthewJA-streams/Real_world_examples/Wetness_stream_gauge_correlations.ipynb

**Comment by MatthewJA** [comment]
Right! my bad

**Comment by MatthewJA** [comment]
Look OK now @robbibt?

**Review by robbibt — APPROVED** [review]
Have made some updates to condense some of the notebook cells so it's easier to follow, and hopefully improved the run time a little using dask (it still takes a very long time to load the data, so in the future it might be good to update this to focus on a smaller area or time period). Good to merge!

**Comment by MatthewJA** [comment]
Thanks for the modifications @robbibt!

**Pull request merged**
