### PR TITLE
Run basic analysis

### PR DESCRIPTION
**Pull request by erialC-P**
_Note: checklist below only relevant if committing to the [`develop`](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop) branch:_

### Proposed changes
This is a placeholder notebook for the new Beginners_guide

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by erialC-P** [comment]
Feel free to add to it but if not, I will continue working on it once back from leave next week.

**Comment by robbibt** [comment]
Hi Claire, I just did a quick tidy of the branch to remove all new notebooks except the one that's specific to the pull request (this will reduce the likilihood of merge conflicts in the future).

Before you do any more work, please run `git pull` to get the latest version of the branch!

**Comment by caitlinadams** [comment]
Hi @alexgleith and @robbibt 

I would appreciate both of your feedback on this notebook -- I've tried to balance the need for this to act both as reference material and as something that can be used in workshops. I've also tried to frame it more as a cohesive analysis, whereas the DIY notebook took you through a bit more of the practicality of loading and plotting, which is handled more by the other beginner notebooks now.

**Comment by caitlinadams** [comment]
Sorry, the changes I made this morning didn't get pushed to github. All sorted now and ready for feedback. Focus on 06_Basic_analysis.ipynb

**Comment by alexgleith** [comment]
This is an excellent notebook!

One minor change I suggest is the colour ramp for NDVI. If it went from red for low to green for high, that would maybe be better.

**Comment by erialC-P** [comment]
Wow! Great notebook!!!!!! I particularly like the extension options that you have provided. It is a really super nice summary of the contents of the beginners guide.

-Only because it is still a beginners notebook, I think that a brief justification for the loaded modules would be useful. 
-In Step 4, you have a markdown cell referencing `dataset.ndvi`. I think this is unneeded in this notebook? 
-In Step 5, I think it would be useful to add that this code will save the GeoTIFF in the same folder from which this tutorial was sourced and from there it can be downloaded for later use (just got my beginners hat on again here)

**Pull request merged**
