### PR TITLE
virtual product transform updates

### PR DESCRIPTION
**Pull request by uchchwhash**
### Proposed changes
Showcase virtual product transforms that can be defined in the catalog YAML.

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [X] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [X] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by uchchwhash** [comment]
Sorry the notebook rendered incompletely. Will resubmit.

**Comment by uchchwhash** [comment]
Looks OK to me now :smile:

**Comment by robbibt** [comment]
Hey @uchchwhash, it still looks like the final few cells haven't run to me - can you do a restart and run all cells and see if that helps?

image


(The rest of the changes look great)

**Comment by uchchwhash** [comment]
@robbibt I think it's fixed now. :grin:

**Comment by uchchwhash** [comment]
BTW how cool is ReviewNB :surfer: :100: :1st_place_medal:

**Review by robbibt — APPROVED** [review]
This looks perfect now, thanks @uchchwhash!

**Pull request merged**
