### PR TITLE
Add new interactive DEA Coastlines app and move all widgets to `dea_tools.app` submodule

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
This PR adds a significantly updated DEA Coastlines widget for interactively extracting shoreline data using coastline transects. This uses the fantastic new widgets framework put together by @caitlinadams  / DE Africa, which I can see becoming something we want to roll out to the rest of our interactive notebooks too.

At the moment, the interactive app includes:

- Selecting a transect from an interactive map
- Uploading multiple transects from GeoJSON or ESRI Shapefile
- Optionally exporting figures or output data
- Changing the map background

https://www.loom.com/share/7a54951e7ecb496e85f679ae16526be3

This PR also follow's DE Africa's lead by relocating interactive widget code to a new `dea_tools.app` submodule so we can more easily keep widget code in one central location (and remove it from `Supplementary_data` so that folder remains just for data, not code). I've updated the existing interactive notebooks to account for this change.

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [X] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [X] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Review by BexDunn — CHANGES_REQUESTED** [review]
The transect extraction widget is incredible!!!! 😮 🥇 

- in future maybe split this PR into 2 PRs - changes to support the new notebook then the notebook itself, it's chonky 

 
Some thoughts on the notebook:


- colour map in statistics widget is struggling a bit around 0 - consider fixing this (not a major) I'm wondering if this is coming in from the WFS as I can't see where this is defined in the app or the script

- does it matter where you start drawing the transect from? I'm guessing yes, but I don't see any guidance on this. Dumb question.
- I'd like a comment under the resulting plot explaining 'along-transect distance' similar to that in the CMI, for dummies like me: e.g. "Negative values indicate that an annual shoreline was located inland of the baseline shoreline" or something to indicate the significance of what we see in the transects. I know the comment below the plot does say this, but I went to look up the CMI because my head didn't quite grasp the significance of the y axis at first go. 


Overall, this is TOTALLY FRICKING INCREDIBLE, and here are a few suggested changes :)

**Comment by BexDunn** [comment]
This is awesome. I have made a couple of suggestions for you

**Comment by robbibt** [comment]
@BexDunn Those are fantastic suggestions, thankyou! And definitely agree about splitting the PR in the future... I realised that about halfway through committing everything, but by then it was too late... 😱 

Will make the other suggested changes and let you know when it's ready!

**Comment by robbibt** [comment]
Hey Bex, have updated the notebook!

> colour map in statistics widget is struggling a bit around 0 - consider fixing this (not a major) I'm wondering if this is coming in from the WFS as I can't see where this is defined in the app or the script

It's coming from Geopanda's new **`.explore` method that plots geodataframes on an interactive map. Unfortunately nothing I can do on my end - it's annoying!

> does it matter where you start drawing the transect from? I'm guessing yes, but I don't see any guidance on this. Dumb question.

Not a dumb question at all, it definitely matters which way you draw it. I've added some new guidance in the notebook and the tool:

image

image

> I'd like a comment under the resulting plot explaining 'along-transect distance' similar to that in the CMI, for dummies like me: e.g. "Negative values indicate that an annual shoreline was located inland of the baseline shoreline" or something to indicate the significance of what we see in the transects. I know the comment below the plot does say this, but I went to look up the CMI because my head didn't quite grasp the significance of the y axis at first go.

Have expanded the explanatory text below the plot:

image


Thankyou, these are great things to clarify!

**Pull request merged**
