### PR TITLE
Renamed all 'Github' to 'GitHub'

### PR DESCRIPTION
**Pull request by benji-glitsos-ga**
### Proposed changes

Since 'GitHub' is the proper capitalisation, I corrected all instances of 'Github' throughout the dea-notebooks repo - this includes changing instances within the Notebooks as well as the Tools code comments (but not within the Python code itself).

Note: We should merge this as soon as possible to avoid merge conflicts.

### CODE REVIEW

**Review by robbibt — APPROVED** [review]
Accepted pending the test run (it failed but may clear up when it runs again)

**Review by BexDunn — APPROVED** [review]
Hi Benji, happy for you to go ahead and merge. Thanks for doing this stuff, it all counts :) I'm not sure whether it would be worthwhile to update the last modified dates on the notebooks, given it's a nice (but relatively minor) change, and I think better not to change the last modified date as it may make people feel that individual notebooks have been reviewed more recently than they have? So happy for this one to go through asap :)

**Comment by robbibt** [comment]
I reckon leave them as they are for now - they're most useful for code changes (e.g. knowing that the code last ran OK on date X). 🙂

**Comment by benji-glitsos-ga** [comment]
Ok great. Thanks for reviewing - I can merge this now.

**Pull request merged**
