### PR TITLE
Added ENSO influence waterbodies notebook

### PR DESCRIPTION
**Pull request by MatthewJA**
### Proposed changes
Added notebook that estimates ENSO influence on DEA Waterbodies.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Review by BexDunn — CHANGES_REQUESTED** [review]
Hey! Looks pretty brilliant. I have changes to request: 1stly just a small one - that sentence about interpolation needs an edit. 2ndly, the sentences where you've discussed the CDF, PDF and the significance tests, you say ' it is obvious that' or similar. Can you please consider replacing that with something like 'because the PDF is higher at wetter percentages/ area under PDF is higher at wetter percentages (or similar) we can see that Kati Thanda is wetter during La Nina events' for each of those explanations? Makes it easier for the casual observer, and for those for whom it may not be obvious! Accessibility = the goodness.

**Comment by BexDunn** [comment]
Looks really good, just trying to get the notebook to run

**Comment by MatthewJA** [comment]
Let me know if there's anything I can do to help get it running @BexDunn!

**Comment by BexDunn** [comment]
Looks like the `wget` request might be getting blocked, but it worked this morning. Is it still working for you?

**Comment by MatthewJA** [comment]
Are you on the NCI or the sandbox?

**Comment by BexDunn** [comment]
> Are you on the NCI or the sandbox?

sandbox

**Review by BexDunn — APPROVED** [review]
NIce work

**Review by robbibt — APPROVED** [review]
Looks great to me! Ready to squash and merge 🚀

**Comment by MatthewJA** [comment]
Thanks @BexDunn and @robbibt, all squished! :)

**Pull request merged**
