### PR TITLE
Add DEAWaterbodies to repo

### PR DESCRIPTION
**Pull request by CEKrause**
_Note: checklist below only relevant if committing to the [`develop`](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop) branch:_

### Proposed changes
Add DEA Waterbodies notebooks to repo

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [NA] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [NA] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
Will go through this this morning! :)

**Comment by CEKrause** [comment]
@robbibt - where is the version of the code with your small changes? I want to get back to this, but I don't want to diverge from the changes you've made.

**Comment by robbibt** [comment]
If you pull the latest changes on your branch I think it should get them... commit e60d4b9 I think?

**Comment by robbibt** [comment]
@CEKrause If you pull the latest changes on your branch I think it should get them... commit e60d4b9 I think?

**Comment by CEKrause** [comment]
Due to the large number of changes in the master branch, this pull request is very stale and difficult to work with. 
I am deleting it here, but will recreate it as a separate request, and have taken into account the feedback provided here.

**Pull request closed without merging**
