### PR TITLE
add csv export to DEA WIT notebook

### PR DESCRIPTION
**Pull request by BexDunn**
### Proposed changes
Adds a csv export to the WIT notebook, explains the data in the export

### Checklist 
(Replace `[ ]` with `[x]` to check off)

- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://knowledge.dea.ga.gov.au/genindex/), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with
- [x] Check for any spelling mistakes using the DEA Sandbox's built-in spellchecker (double click on markdown cells then right-click on pink highlighted words). For example:

sandbox_spellchecker

### CODE REVIEW

**Comment by BexDunn** [comment]
I haven't managed to catch the previously updated knowledge hub links in this correctly, so have converted it to draft for now

**Review by LaurenSchenk1 — APPROVED** [review]
Everything looks good to me :)

**Comment by benji-glitsos-ga** [comment]
Hi Bex,

It looks great. Some minor notes about the links:

* When linking to a KH product, you don't need to include the `?tab=overview` part at the end. The link can just be: <https://knowledge.dea.ga.gov.au/data/product/dea-coastlines/>
* Instead of linking to the datahandling github file, you can link to the API documentation which also links to the source code: <https://knowledge.dea.ga.gov.au/notebooks/Tools/gen/dea_tools.datahandling/>

**Review by robbibt — APPROVED** [review]
Hey @BexDunn, this looks great to me. Two small suggestions:
1) Change the Explorer links from "https://explorer.sandbox.dea.ga.gov.au/products/..." to ""https://explorer.dea.ga.gov.au/products/..." (our public facing URLs are now "https://explorer.dea.ga.gov.au" for AWS and "https://explorer.nci.dea.ga.gov.au" for NCI)
2) For links to notebooks and Python code, I'd personally prefer for us continuing to use relative links wherever possible rather than an external link to Knowledge Hub - it means that users can quickly open up the code directly on the Sandbox, but should still work in the rendered notebooks on Github and Knowledge Hub. So, I'd potentially prefer the one on the left here to the one on the right: 
image

(I think you can still link to specific notebook headers in the same way you have already, just keeping the relative part of the link at front)

**Pull request merged**
