### PR TITLE
New notebook for loading data from Microsoft Planetary Computer

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
This PR adds a new notebook for loading data from Microsoft Planetary Computer and combining it with DEA data, including:

- How to use pystac_client to search for ESA WorldCover data for a study area and time period
- Load ESA WorldCover from Planetary Computer into the notebook using `odc.stac`
- Compare ESA WorldCover outputs against DEA's Land Cover product
- Load a time series of USGS Collection 2 Landsat surface temperature from Planetary Computer
- Add this data to a time series of DEA Landsat ARD so they can be analysed together

image

image

### Closes issues (optional)
- Closes Issue #1088 

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Review by jmettes — APPROVED** [review]
This is great! Very useful to have examples of using them together.

**Review by geoscience-aman — APPROVED** [review]

**Comment by robbibt** [comment]
<p>Great idea, will try it out</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1097/discussion/#comment-1619510023'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Neat, will do</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1097/discussion/#comment-1619510052'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Yes, absolulety - will update</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1097/discussion/#comment-1619510061'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Actually, I might switch to a more intuitive cmap and strip out the legends completely, they don't really do much here</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1097/discussion/#comment-1619510052'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Will do a teal "info" box instead, feels friendlier!</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1097/discussion/#comment-1619510023'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
