### PR TITLE
Update legacy ARD to C3 ARD

### PR DESCRIPTION
**Pull request by geoscience-aman**
I updated the ARD product references from Legacy (`s2._ard_granule`) to Collection 3 (`ga_s2.m_ard_3`).

Due to other issues, I have excluded `'Real_world_examples/Sentinel_2_waterbodies.ipynb'` and `'Scientific_workflows/TSmask/TSmask.ipynb'` from this PR. I have tested all other affected notebooks on the Sandbox.

### CODE REVIEW

**Comment by robbibt** [comment]
Hey @geoscience-aman  @uchchwhash I'll try and have a look at this ASAP, looks great so far from a quick glance. One question: given it seems like the `*_provisional_3` products are going to be retired and all NRT data that used to be in those products will be contained in the new `*_ard_3` products going forward, would it be a good idea to remove the `*_provisional_3` products from the repo in this same PR? That way we'd prevent us having to go back and do another big update to remove them later on

**Comment by geoscience-aman** [comment]
> Hey @geoscience-aman @uchchwhash I'll try and have a look at this ASAP, looks great so far from a quick glance. One question: given it seems like the `*_provisional_3` products are going to be retired and all NRT data that used to be in those products will be contained in the new `*_ard_3` products going forward, would it be a good idea to remove the `*_provisional_3` products from the repo in this same PR? That way we'd prevent us having to go back and do another big update to remove them later on

Thanks Robbi. Thoughts? @uchchwhash

**Comment by uchchwhash** [comment]
@geoscience-aman I am happy for us to merge this for now, and maybe up next is looking at removing the provisional product references.

**Review by uchchwhash — APPROVED** [review]
Awesome work!

**Pull request merged**
