### PR TITLE
Notebook demonstrating cloud masking

### PR DESCRIPTION
**Pull request by uchchwhash**
### Proposed changes
- Add notebook showing how to create and apply masks

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [X] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [X] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by BexDunn** [comment]
@uchchwhash why does fmask automatically mask water? I think that's not desirable behaviour for many of the science analyses.

**Comment by uchchwhash** [comment]
@BexDunn it does not automatically mask water though. It classifies the water pixels, and it is upto you whether you want to keep it or not. You could set your mask to be valid or water or snow... if your application mandated it.

Do you have any changes to the notebook in mind about this?

**Comment by uchchwhash** [comment]
@robbibt in case you are reviewing this, I updated the notebook after talking to @BexDunn, she had a couple of very helpful suggestions that have since been incorporated into the notebook.

**Comment by robbibt** [comment]
@uchchwhash Yep, I've just checked out version 47cc65e, is that OK? The combination of the three flags change is something I was going to comment about too, so that's a great addition

**Comment by robbibt** [comment]
@uchchwhash I just pushed an update to the notebook. The main change is some extra background up the top, and I moved the `dilate` function to `dea_datahandling` so that it's re-usable. Can you check/revise the documentation for that function to make sure I got everything right? 

Other than that, happy to accept this!

**Comment by uchchwhash** [comment]
Looks ok to me! :+1:

**Pull request merged**
