### PR TITLE
spatial wit - pending documentation

### PR DESCRIPTION
**Pull request by BexDunn**
### Proposed changes
This is a testing version of the Spatial WIT notebook. It only runs on the NCI at the moment. Once the documentation is complete, and collection 3 along with Fractional Cover and WOfS are available on the Sandbox, we'd like to bring it into the sandbox. 

-  ease of use
- documentation
- additions?

### Checklist (replace `[ ]` with `[x]` to check off)
- [x ] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [ ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [ ] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [ ] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by emmaai** [comment]
Not sure if the output of cells are kept intentionally? But it's kinda difficult for future change.

**Comment by LeoLym** [comment]
The current version of spatial WIT doesn't capture large WIT's along the same Landsat path.  Scenes along the same path are acquired seconds apart and can safely be combined, scenes from adjacent (east or west rather than north or south) rows can't be safely combined because they're acquired 8 days (or more) before/after that scene.

**Comment by robbibt** [comment]
Hey @BexDunn , is this still a live PR? (just doing an early spring clean of our open PRs/issues!)

**Comment by BexDunn** [comment]
> Hey @BexDunn , is this still a live PR? (just doing an early spring clean of our open PRs/issues!)

Hey @robbibt - it's not dead, just sleeping ;) This PR is waiting on progress on our documentation, and waiting on C3.

**Comment by emmaai** [comment]
Can we merge this first so that we can keep track of change from PR #790 ? @BexDunn

**Comment by BexDunn** [comment]
So, we need this PR approved in order to get the AWS spatial WIT in. This doesn't tick all the boxes, because we need the other PR on top of this plus changes.

**Pull request merged**
