### PR TITLE
Add notebook demonstrating reprojection using geoboxes

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
This notebook covers a common use case: trying to combine `datacube` data with external rasters that may not share the same spatial grid. It introduces users to datacube's `GeoBox` which currently doesn't feature much in the User Guide despite being incredibly useful for many spatial tasks. It demonstrates how to perform common reprojection tasks, including: 

1. Loading and reprojecting datacube data to match a raster file using `dc.load`
2. Reprojecting existing datacube data to match a raster using `xr_reproject`
3. Loading and reprojecting a raster to match datacube data using `rio_slurp_xarray`

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [X] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [X] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
Hey @Kirill888 , if you have a spare moment it'd be great if you could quickly skim through this and let me know if I've mischaracterised `GeoBox`s anywhere, or suggested sub-optimal ways of going about re-projection

**Comment by Kirill888** [comment]
yeah sorry, my bad, in the second case `gbox=` has to be named, and yes it should be renamed into `geobox=`.

**Comment by robbibt** [comment]
Hey @Kirill888 , have made some small updates to account for your comments above, and tagged you as a reviewer. Would you mind accepted this PR if it looks good to you now?

https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/commit/5cc3240b67cdac4d90b7b57a0b6dae1a0db99939/

**Review by Kirill888 — APPROVED** [review]
looks good

**Pull request merged**
