### PR TITLE
Added subpixel waterbodies notebook

### PR DESCRIPTION
**Pull request by MatthewJA**
Added a notebook that uses subpixel contours to find waterbody edges, and calculates a time series based on this, for a given waterbody.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)

### CODE REVIEW

**Review by BexDunn — APPROVED** [review]
That's super cool. I'm pretty happy with it. It could be handy to have an option to export the new waterline as a poly?

**Comment by MatthewJA** [comment]
Great idea @BexDunn, I'll add that.

**Comment by BexDunn** [comment]
Oh hey, you also need to add this to the Real_world_examples rst so it shows up in the index

**Comment by MatthewJA** [comment]
@BexDunn done!

**Review by BexDunn — APPROVED** [review]

**Pull request merged**
