### PR TITLE
Intro to loading data

### PR DESCRIPTION
**Pull request by erialC-P**
_Note: checklist below only relevant if committing to the [`develop`](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop) branch:_

### Proposed changes
This is a placeholder notebook for the new Beginners_guide

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by erialC-P** [comment]
Feel free to add to it but if not, I will continue working on it once back from leave next week.

**Comment by robbibt** [comment]
@erialC-P I just did a quick tidy of the branch to remove all new notebooks except the one that's specific to the pull request (this will reduce the likelihood of merge conflicts in the future).

Before you do any more work, please run `git pull` to get the latest version of the branch!

**Comment by erialC-P** [comment]
Having viewed available products and measurements, users are introduced to querying in this notebook. dc.load, customisation options for dc.load and how to read your xarray are discussed.
To see where this notebook is designed to sit within the Beginners Guide folder, please see:
https://github.com/GeoscienceAustralia/dea-notebooks/wiki/DEA-notebooks-refresh:-notebook-allocations

**Comment by erialC-P** [comment]
I think the code formatting was an artefact of a copy/paste that I performed from an earlier notebook. I'm happy to fix this up and incorporate the suggested changes

**Comment by robbibt** [comment]
@caitlinadams @erialC-P The code formatting was me - I somewhat deliberately changed the formatting from strict Black to line up some of the function calls to avoid the trailing `[` and ']` that Black likes to do... I just felt that the `dc.load` calls were a bit easier to read for beginner users if all of the arguments are nicely lined up. The stray `'` and misaligned args should definitely be fixed up though! 

Since I have the notebook already open, I'll quickly fix up those changes

**Comment by erialC-P** [comment]
My suggestions:
Comments:
- be a little more explicit in the link between the Xarray DataArrays and Dataset
- really briefly describe how keyword dictionary unpacking works (specifically the role of the **)

**Comment by erialC-P** [comment]
- is it too unconventional to add a screenshot of what the progress bar looks like during data loading?

**Pull request merged**
