### PR TITLE
Added seasonality notebook

### PR DESCRIPTION
**Pull request by MatthewJA**
This PR adds a notebook that shows a few ways to detect and visualise seasonality in time series data. I've asked myself several times "is this time series seasonal?" or "has my deseasonalisation worked?" and this is a set of useful tools for helping to understand that.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
This looks really great - nice and clear code and great documentation that nicely walks users through the steps. Some minor comments:
- Can you replace the link in the hyperlinked product name at the top to CMI instead of the website (e.g. https://cmi.ga.gov.au/data-products/dea/456/waterboards)? It's a more useful landing page for users that want more info I think (DEA Waterbodies is an anomaly in that there's no Explorer page; in time we may want to update all of the hyperlinked Explorer links to point to CMI too...)
- Please add this notebook to the README.rst file so it will render on the User Guide

A more general question... how do these workflows go when applied directly to irregularly spaced timestamps such as satellite observations rather than evenly spaced weekly data? Just thinking that many users may want to detrend raw data loaded directly from the datacube rather than apply any temporal interpolation, and it would be nice to give them tools to do so.

**Comment by MatthewJA** [comment]
Detrending on uneven data is generally not supported. My approach to this is to upsample the data to weekly and interpolate over it, which should give you good results - then you can always reindex the seasonal trend onto the original time index and subtract it off that way. This particular notebook will work fine on unevenly sampled data because I implement this interpolation step, and there's an analogous function in xarray that'll do the same thing.

**Comment by robbibt** [comment]
Yep OK, no worries - I wonder if it's worth including a note to that effect in the notebook near the section that you do the interpolation?

**Comment by MatthewJA** [comment]
Added to the readme, changed the URL, added a note about interpolation

**Review by robbibt — APPROVED** [review]
Looks great to me!

**Pull request merged**
