### PR TITLE
Add new func for plotting fmask data with automatic colours

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
Add new func for plotting fmask data with automatic colours. This matches the existing `plot_wo` function by @MatthewJA

### CODE REVIEW

**Review by CEKrause — APPROVED** [review]
Looks good. Super neat.

**Comment by robbibt** [comment]
Forgot to include an example:
fmask_parallax_comparison_ga_s2bm_oa_provisional_3-2-1_54HTG_2021-09-11_nrt_fmask_parallax_off

**Review by BexDunn — APPROVED** [review]
Looks good. What is the try/except around the Attribute error handling?

**Comment by robbibt** [comment]
@BexDunn That's code inherited from `plot_wo` - not exactly sure what the original intention was for that. @MatthewJA?

**Comment by MatthewJA** [comment]
Shenanigans for dealing with xarray...

**Comment by MatthewJA** [comment]
imshow is _way_ faster (/works when pcolormesh doesn't) but not always supported, maybe version-dependent? maybe type-based? Not sure. That's what the try/except is for.

**Review by MatthewJA — APPROVED** [review]
LGTM

**Pull request merged**
