### PR TITLE
Notebook coastalerosion

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
Updated the coastal erosion notebook to use the new template, and moved over all necessary functions required for the notebook.

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by caitlinadams** [comment]
Hey @robbibt, this is looking great. Having a quick read through, I noticed that under the "Compute Modified Normalised Difference Water Index" section, you have a hyperlink to the research paper. What do you think about changing this to be a citation that's hyperlinked, similar to the paper reference in the NDCI notebook?

**Comment by robbibt** [comment]
@caitlinadams  No problem, will update. I've just tried testing the notebook on the NCI and the Collection 3 database seems to be out of action, which means that right now, all the other "NCI compatible" notebooks will cause errors too...

**Comment by cbur24** [comment]
Really nice case study, @robbibt. One quick comment, is it possible to get a color ramp on the shoreline migration plot to make it obvious that the red colours indicate more recent shorelines?  Maybe this is already implemented on the interactive plot (I just read the notebook, I haven't run it), in which case ignore this.

**Comment by robbibt** [comment]
@cbur24 I'd really like a key on that figure too, although custom legends are always a hassle in matplotlib! I'll see if there's an easy option

**Comment by robbibt** [comment]
@caitlinadams @cbur24 Have made both your requested changes (Geopandas made adding a colourbar easy!). If you're happy I think it should be OK to have this merged in even though we can't test it on the NCI - we can come back and test it at the end before we make `develop` the new `master`

**Pull request merged**
