### PR TITLE
Add updated DEA High and Low Tide Imagery notebooks

### LINKED ISSUE #669: Update DEA_notebooks folder to include High/Low Tide Composite
From Issue #615.

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
This PR adds a simple DEA Datasets notebook for the DEA High and Low Tides Imagery product suite.

I've tried to keep this really simple and direct, base the text directly from the [CMI listing](https://cmi.ga.gov.au/data-products/dea/133/dea-high-and-low-tide-imagery-landsat), and to cover the following steps:

- Inspecting the products and measurements available in the datacube
- Loading low and high tide data for a coastal location
- Plotting low and high tide data in true and false colour
- Converting low and high tide data to a remote sensing water index (NDWI), and use this to map wet pixels at low and high tide

### Closes issues (optional)
- Closes Issue #669 

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [X] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
Can whoever reviews this please also critique this as a potential structure/template that we could use for other DEA Datasets notebooks? It would be fantastic if all of the notebooks in this folder could follow a reasonably similar structure so it's easy for users to get started with all of our different products.

**Comment by MatthewJA** [comment]
> Can whoever reviews this please also critique this as a potential structure/template that we could use for other DEA Datasets notebooks? It would be fantastic if all of the notebooks in this folder could follow a reasonably similar structure so it's easy for users to get started with all of our different products.

I wonder if each notebook should stand individually (explaining datacube, list products, etc) or whether reading the beginner's guide should be assumed.

**Review by MatthewJA — APPROVED** [review]
LGTM, nice notebook. Simple and to the point with a nice example at the end. Runs real fast.

**Comment by robbibt** [comment]
@MatthewJA I think we can probably assume users have gone through the Beginner's Guide (we could always add this as a pre-req at the top of DEA dataset notebooks to make this nice and clear?). My intention for including the list products bit was to basically explain what products are available via code, rather than listing them directly in the markdown (e.g. and give users strategies they can use themselves to find relevant products). Not sure if it will be too repetitive though?

**Comment by MatthewJA** [comment]
I think it's good to include list products here, I just found the description wordier than I perhaps expected. But it's totally fine as it stands

**Pull request merged**
