### PR TITLE
Updates to DEA Waterbodies notebooks and tools for v3.0

### PR DESCRIPTION
**Pull request by BexDunn**
### Proposed changes
Updates to DEA Waterbodies notebooks and tools to support DEA Waterbodies v3.0

### Checklist 
(Replace `[ ]` with `[x]` to check off)

- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex/), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
[ ] Test notebook on both the `NCI` and `DEA Sandbox`  - I haven't tested it on the NCI, but I haven't made any major changes and haven't logged into NCI for a very long time...
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with
- [x] Check for any spelling mistakes using the DEA Sandbox's built-in spellchecker (double click on markdown cells then right-click on pink highlighted words). For example:

sandbox_spellchecker

### CODE REVIEW

**Comment by whatnick** [comment]
Please see the concurrent v2/v3 support I have proposed here : https://github.com/whatnick/dea-notebooks/blob/feat/waterbody-version/Tools/dea_tools/waterbodies.py

**Comment by benji-glitsos-ga** [comment]
It's looking really good. I'm just wondering, should the Disclaimer be under a heading, similar to the following 'Applications' section? This is because the disclaimer is two paragraphs long.

**Comment by robbibt** [comment]
This is looking awesome @BexDunn! Re the disclaimer, we have a precedent for using alert boxes for this kind of thing, e.g.:
image

I wouldn't recommend a bright red one like this, but we could probably pop it in a [blue or yellow alert](https://www.ibm.com/docs/en/watson-studio-local/1.2.3?topic=notebooks-markdown-jupyter-cheatsheet) if we wanted to make it a bit more obvious. 🙂  (personally I'd like to expand our use of alert boxes like these throughout the repo - I think they catch the eye nicely and [follow best practice from recent papers, e.g. section 3.2 here](https://www.mdpi.com/2072-4292/14/14/3359))

**Comment by benji-glitsos-ga** [comment]
I didn't think of this sooner @BexDunn - in the notebook file, could we change all the Knowledge Hub links to point to the new URL? There are four links that point to "docs.dea.ga.gov.au" but they can be changed to "knowledge.dea.ga.gov.au".

E.g.

```
[DEA Waterbodies](https://docs.dea.ga.gov.au/data/product/dea-waterbodies-landsat)

... change to ...

[DEA Waterbodies](https://knowledge.dea.ga.gov.au/data/product/dea-waterbodies-landsat)
```

**Review by robbibt — APPROVED** [review]
Looks awesome!

**Pull request merged**
