### PR TITLE
Update coastal scripts and notebooks to use FES2014 tidal model

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
This PR updates DEA Notebooks to use the newly installed and set-up FES2014 tidal model. In the future, the plan is that this may replace the current tidal model we use in the Sandbox (OTPS), because it is difficult to install and has a dubious/unclear license. 

The PR updates tide modelling scripts inside `dea_tools.coastal` to use FES2014, but for continuity the older OTPS functions have been kept in the script but renamed with an "_otps" suffix (this will allow users to continue to use the older functions if they prefer).

The current `Tide_modelling.ipynb` notebook has been majorly refreshed to document these new functions and account for the change in tidal model, and the two Real world example notebooks (`Coastal_erosion.ipynb` and `Intertidal_elevation.ipynb`) updated to use the new funcs.

To test this PR, I think the easiest way might be to checkout this branch, then run the `Tide_modelling.ipynb` notebook from start to finish and see if anything breaks/doesn't make sense?

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Review by BexDunn — APPROVED** [review]
I can run the tidal modelling notebook, and it looks good to me.

**Review by margaretharrison — COMMENTED** [review]
ignore this sorry!

**Comment by erialC-P** [comment]
I worked through `Tide_modelling.ipynb` and it all looked good to me. The only thing that I noticed was a formatting issue: the cell outputs from the previous run were still present when I opened the notebook and need clearing. Otherwise, thanks for pushing this update through!

**Review by erialC-P — CHANGES_REQUESTED** [review]
Content all looks great! Thanks for these updates Robbi! Only change required is a formatting one - the cell outputs could be cleared from the previous run.

**Comment by robbibt** [comment]
> Content all looks great! Thanks for these updates Robbi! Only change required is a formatting one - the cell outputs could be cleared from the previous run.

Thanks Claire! I think our current policy is to run the entire notebook so that all the outputs are saved; that way they appear nicely formatted in the User Guide (there's always been an aspiration to find some way to wipe the outputs by the time they get loaded into the Sandbox, but I don't think we've every progressed that yet)

**Review by margaretharrison — APPROVED** [review]
Great work!! They all run for me!! I fixed up a few typos in the tidal modelling notebook - I hope I submitted them correctly. If not let me know and I'll try fix it!

**Comment by robbibt** [comment]
Thanks so much @margaretharrison, good catches! If everyone is OK with it, I think I'll merge this PR now (happy to make any further changes as a new PR layer on too)

**Pull request merged**
