### PR TITLE
Add new STAC metadata notebook

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
This PR adds a new notebook intended to provide a brief introduction to accessing and using DEA's STAC metadata:

1. - How to construct a STAC metadata API call
2. - How to search for STAC metadata and load the results into Python
3. - How to inspect and plot the unique STAC Items contained in the metadata
4. - How to inspect assets contained within a STAC Item
5. - How to download data using STAC metadata
6. - How to stream data into QGIS using STAC metadata (without downloading it first)

I'd love to hear any suggestions for improving this (either technical or regarding correct terminology), or any ideas for additional things to include. For example, in the future I'd love to add a section explaining how to iterate though large multi-page search outputs etc.

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [X] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [X] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by alexgleith** [comment]
I LOVE it @robbibt!

Only suggestion I have is that we could emphasise loading an XArray from the S3 URI instead of downloading first, but I think the use of QGIS is really cool too.

**Review by alexgleith — APPROVED** [review]

**Comment by robbibt** [comment]
@alexgleith Yep, that would be a nice addition to the notebook, I agree! Will add something in

**Comment by robbibt** [comment]
Hey @alexgleith , have added examples on streaming data to an `xarray` using `xr.open_rasterio`, and also how to use `from datacube.testutils.io import rio_slurp_xarray` to load data from the cloud and resample to match data loaded via `dc.load`

**Review by alexgleith — APPROVED** [review]
Love it!

**Pull request merged**
