### PR TITLE
Update notebooks to use C3 derivatives

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
This PR updates notebooks in the repo to use the newer Collection 3 geomedian and FC percentiles products.

The tests also need to be updated to point to the new products, but we can do that as a later PR.

### Closes issues (optional)
- Closes Issue #916

### CODE REVIEW

**Comment by robbibt** [comment]
@cbur24 Tagged you as I made a bunch of changes in the ML notebooks, mainly to swap to the new data, but also some other things that were causing issues (e.g. there was a bit that dropped several columns off the training data to drop x/y data, but it was removing valid data so I got rid of it... everything seems to work OK though)

**Review by Kooie-cate — APPROVED** [review]
awesome, all the substitutions look good, notebooks all tested no problems found with any of them.

**Comment by Kooie-cate** [comment]
this might be a question for @cbur24, in Scaleable_machine_learning/4_Classify_satelite_data` cell 16 throws this error repeatedly `UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = min(effective_n_jobs(n_jobs), n_estimators)` 
I just wanted to make sure this wasn't a **new thing**, if this is a known thing that's just a result of using Dask with these modules, that's all good, It dosn't stop the notebook working. 

gosh sorry everyone I clicked the wrong button

**Review by erialC-P — APPROVED** [review]
Reviewed all and happy to approve.

**Comment by robbibt** [comment]
Thanks @Kooie-cate and @erialC-P! I'll merge this PR, but Chad should still be able to comment here about the `Loky-backed parallel loops` issue

**Comment by cbur24** [comment]
@robbibt @Kooie-cate 
The `Loky-backed parallel loops` issue happens because the model that's output in the previous notebook has the `n_jobs` parameter set as > 1, which doesn't gel with dask handling the parallelism.  To fix this open the model (cell `[5]`) with the following call:

`model = load(model_path).set_params(n_jobs=1)`

**Pull request merged**
