### PR TITLE
Classificationtools

### PR DESCRIPTION
**Pull request by s-m-t-c**
_Note: checklist below only relevant if committing to the [`develop`](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop) branch:_

### Proposed changes
Include a brief description of the changes being proposed, and why they are necessary.

### Checklist (replace `[ ]` with `[x]` to check off)
- [ ] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X ] Remove any guidance cells (e.g. `General advice`)
- [X ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [ ] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [ ] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by caitlinadams** [comment]
I think if you change this merge from "into master" to "into develop", that should avoid the conflicting files!

**Comment by robbibt** [comment]
Looking forward to seeing a notebook covering these too, I think it would be really useful for demonstrating how to use them

**Comment by danclewley** [comment]
> Looking forward to seeing a notebook covering these too, I think it would be really useful for demonstrating how to use them

These are the notebooks and scripts where we are using the functions for the LCCS project https://bitbucket.org/au-eoed/livingearth_lccs_development_tests/src/ml_notebook/notebooks/cultivated_ml/

**Comment by s-m-t-c** [comment]
@robbibt I have made the requested changes, let me know if they are what you were thinking of. Regarding the geomedian it can be also be implemented spatially and is a bit more robust than the mean according to Dale.

**Comment by robbibt** [comment]
@s-m-t-c OK, have made some minor updates largely to the function docstrings for concistency with PEP8 and the Scipy/numpy docstring formats, other than that it looks great - happy for me to accept/merge it it?

**Comment by s-m-t-c** [comment]
@robbibt looks fine, thanks pepwizard. Merge away!

**Pull request merged**
