### PR TITLE
Export to NetCDF

### PR DESCRIPTION
**Pull request by benjimin**
Tested on both VDI and sandbox.

### CODE REVIEW

**Comment by BexDunn** [comment]
looks good to me

**Comment by caitlinadams** [comment]
Yes, sorry, I got partway through this today. Will pick up on Monday if that's ok! I've just got a few minor comments about it

**Comment by robbibt** [comment]
Comments addressed and notebook incorporated by #446

**Comment by robbibt** [comment]
Comments addressed and notebook incorporated by #446

**Pull request closed without merging**
