### PR TITLE
Add DEA Landsat Collection 3 notebook

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
This PR adds a much over-due DEA Datasets notebook that demonstrates how to load data from DEA Landsat Collection 3 Surface Reflectance products using the Digital Earth Australia datacube. Topics covered include:

- Inspecting the Landsat products and measurements available in the datacube
- Loading Landsat data for specific location and time
- Plotting Landsat data in true and false colour
- Applying a cloud mask using the oa_fmask band
- Advanced: Loading data in its native projection and resolution

Most of the markdown is based directly on CMI, and I've tried to direct users back towards CMI for more info at every opportunity.

### Closes issues (optional)
- Closes Issue #665

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
Hey @sixy6e, have just tagged you as a reviewer to have a quick check of the science and whether I've mischaracterised anything when paraphrasing CMI.

@Kirill888: can you briefly check the "native load" bit at the end?

**Comment by robbibt** [comment]
This PR partially addresses #601 and #620

**Comment by MatthewJA** [comment]
There's a few grammar things that I'll fix/change and push to the branch. My only other issue with the wording is that it's kind of repetitive - there's several places where the notebook spruiks the benefits of consistent data and how they can be used over time, which pads out some already pretty long sections, for example.

**Comment by robbibt** [comment]
Thanks @MatthewJA! Yeah, most of the text is taken directly from CMI as on one hand I didn't want to re-invent the documentation, but on the other hand it would definitely be nice to make the notebook as simple and streamlined as we can

**Comment by MatthewJA** [comment]
I think one easy-ish change to the doco would be to define all the technical stuff at the start, remove the advertisements for corrected data later on, and keep the markdown cells that are intermingled with code as related to the code as possible. There's a _lot_ of technical details here that I'm not sure are entirely needed to understand how to use Landsat data.

**Comment by sixy6e** [comment]
@robbibt Sorry for the delay, I'll take a look tomorrow.

**Comment by robbibt** [comment]
No worries @sixy6e, there probably isn't much to review as most of the content is from CMI anyway

**Comment by robbibt** [comment]
@MatthewJA I've made some small updates:

- Added the NBAR/NBART figure from DEA Beginners. I experimented with plotting the data directly in the notebook, but unfortunately the Sandbox only contains NBART data so this wasn't possible without restricting the notebook to the NCI
- Simplified the NBAR/NBART sections to reduce some duplication, and printed the measurements detail up top so they give context to the explanations of the sub products (I didn't want to move this any higher as it would create a bit of a wall of text up the top, and wanted the explanatory text to appear in-line next to the list of measurements)
- Re-written and simplified the FMask section.
- The Native load bit is still a bit lengthy, but maybe it's OK since it's in the "Advanced" section at the bottom? Happy to simplify this further if needed 👍 
- Some minor grammar and wording fixes 

https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/commit/72cdf4f9e3e414691c614d1a59024429891ac10d/

**Comment by sixy6e** [comment]
Looks great. The top-level information is still there even after your latest update which is good.  The point on duplication is tricky, as CMI presents the information as a story that you can bail out on at any point depending on how much technical information you want to read into.  Whereas, the notebooks don't really cater to that design being a sequential process.

In the section sub-titled

### What this product offers

I'd recommend inserting links for the sub-products.  eg from this:

* Surface Reflectance NBAR 3 (Landsat 5 TM)
* Surface Reflectance NBART 3 (Landsat 5 TM)
* Surface Reflectance Observation Attributes (OA) 3 (Landsat 5 TM)

into:

* [Surface Reflectance NBAR 3 (Landsat 5 TM)](https://cmi.ga.gov.au/data-products/dea/367/dea-surface-reflectance-nbar-landsat-5-tm)
* [Surface Reflectance NBART 3 (Landsat 5 TM)](https://cmi.ga.gov.au/data-products/dea/477/dea-surface-reflectance-nbart-landsat-5-tm)
* [Surface Reflectance Observation Attributes (OA) 3 (Landsat 5 TM)](https://cmi.ga.gov.au/data-products/dea/369/dea-surface-reflectance-oa-landsat-5-tm)


That way those that seek further technical information, as well as examples of data usage that are outside of the context of this example notebook, can be directly pointed at the product descriptions.

For the section

### Native load

Is it worth including a caveat on the native load?  For instance, using the `mostcommon_crs` function in order to load data in its native CRS and resolution will be fine if constraining the query to a single acquisition. But if extending the spatial extent so that it crosses UTM zones, the user is likely to have the data reprojected and resampled.

**Comment by robbibt** [comment]
OK, have made some updates for @sixy6e's comments here, adding in CMI links and a caveat around native loading on UTM zone boundaries (good catch!):
https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/commit/5c9858b73e3d6dc4789adf0de074724bffb3b560/

I have also added a section at the end that documents how to filter Landsat data by datacube product metadata like `cloud_cover` and GQA geometric accuracy (some wording here reviewed by @lanweiwang):

https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/commit/2bbf504d01984305cf776541aac680903a53eab6/

Anyone have any extra comments on this before we merge it it?

**Comment by sixy6e** [comment]
I just had another read through from your latest changes.  Looks good from my end.

**Comment by robbibt** [comment]
Hey @BexDunn and @CEKrause, I just tagged you on this in case you want to have a quick look at this - I want to merge it but still need one accepted review! 😆

**Comment by BexDunn** [comment]
> Hey @BexDunn and @CEKrause, I just tagged you on this in case you want to have a quick look at this - I want to merge it but still need one accepted review! 😆

I'll have a quick look now, sorry @robbibt :)

**Review by BexDunn — APPROVED** [review]
Looks good to me. Nice to see lots of images.

**Review by CEKrause — APPROVED** [review]
Awesome notebook. I fixed a couple of typos, but it looks brilliant.

**Comment by robbibt** [comment]
Awesome, thanks everyone!

**Pull request merged**
