### PR TITLE
set up a preliminary pull request template

### PR DESCRIPTION
**Pull request by uchchwhash**
New pull requests from now on should have this template in this box when they are created for the user to edit. Feel free to suggest/apply changes to the wording and/or items.

### CODE REVIEW

**Comment by robbibt** [comment]
I was just looking into setting this up! Thanks @uchchwhash .

This looks like a good start to me... I'd be happy to accept this pull request, then start a new draft pull request for future changes like we're doing with the template file?

**Comment by uchchwhash** [comment]
@robbibt works for me!

**Comment by caitlinadams** [comment]
That sounds smart, @robbibt. I'm happy with that too. I think it's good to use draft PRs for items we'd like multiple people to contribute to/review. That means the PRs summarise what features people are actively working on.

**Comment by caitlinadams** [comment]
Oops -- just realised this probably should have been merged into `develop`, rather than `master`

**Comment by robbibt** [comment]
@caitlinadams I might be corrected by @uchchwhash , but from reading about pull request templates I got the impression they only work/github only reads them when they're created on the `master` branch

We'll have to remember to copy it across to `develop` later before we merge it into `master`

**Comment by caitlinadams** [comment]
Well, if it looks like it's working, then it's all fine :)

**Pull request merged**
