### PR TITLE
Add DEA Waterbodies code to repo

### PR DESCRIPTION
**Pull request by CEKrause**
### Proposed changes
Add DEA Waterbodies code and toolkit to repo.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
@CEKrause Such an amazing and well documented set of notebooks! Some very minor issues below. 

Is the plan to have this rendered to the DEA User Guide? If so, there might be a few extra minor issues that I haven't flagged below (e.g. some issues with Sphinx being picky about multiple fomatting like combining code strings with urls etc). 

At some point, we should try and document the requirements for adding content to the `Scientific workflows` folder to make it clear that there's more flexibility here than some of the other folders. 


**TurnWaterObservationsIntoWaterbodyPolygons.ipynb**
- The logo in the top-right of the notebook isn't rendering. Can you check it's pointing to the right level e.g. `../..` etc
- Change `Notebook currently compatible with the NCI|DEA Sandbox environment if you set your filepaths to the required datasets.` to `Notebook currently compatible with both the NCI and DEA Sandbox environments if you set your filepaths to the required datasets.`
- The link for `Bureau of Meteorology's Geofabric v 3.0.5 Beta (Suface Hydrology Network)` doesn't seem to work for me... it's an ftp link so maybe that's the problem? Might need to include the entire url in plain text too so people can use it

**CalculateObservationsThatWentIntoWaterBodyIdentification.ipynb**
- "NCIenvironment" in `Compatability: Notebook currently compatible with the NCIenvironment only` needs an extra space
- Change `Loop through each file and make a note of it's length` to `Loop through each file and make a note of its length`

**IdentifyTimeWaterbodyExceedsXpc.ipynb**
- "NCIenvironment" in `Compatability: Notebook currently compatible with the NCIenvironment only` needs an extra space
- For some reason the `[`RemoveRiversfromWaterBodyPolygons.ipynb`](./RemoveRiversfromWaterBodyPolygons.ipynb)` link brings up a page that says `Unknown type`... would changing it to `[`RemoveRiversfromWaterBodyPolygons.ipynb`](RemoveRiversfromWaterBodyPolygons.ipynb)` help? Not sure 

image

**QuickPlotofWaterBodyTimeseries.ipynb**
- "NCIenvironment" in `Compatability: Notebook currently compatible with the NCIenvironment only` needs an extra space
- If you want to get rid of the `Text(0.5, 1.0, 'Percentage of total surface area observed as wet for ID r4f2epyvw')` text, could try putting a `;` at the end of the last line, e.g. `plt.title(f'Percentage of total surface area observed as wet for ID {WaterID}');`

**RemoveRiversfromWaterBodyPolygons.ipynb**
- "NCIenvironment" in `Compatability: Notebook currently compatible with the NCIenvironment only` needs an extra space
- Same issue with `Bureau of Meteorology's Geofabric v 3.0.5 Beta (Suface Hydrology Network)` link not working
- `GenerateWaterBodyPolygons.ipynb` link leads to a page that says "Not found".

**CreateAustralianCoastlineUsingITEM.ipynb**
- "NCIenvironment" in `Compatability: Notebook currently compatible with the NCIenvironment only` needs an extra space

**DEAWaterbodiesThresholdSensitivityAnalysis.ipynb**
- "NCIenvironment" in `Compatability: Notebook currently compatible with the NCIenvironment only` needs an extra space

**Comment by CEKrause** [comment]
@robbibt Links to the BoM's Geofabric ftp site are blocked on GA computers using Chrome, but work in IE. I want to keep the link to the ftp site since the parent web page is a bit confusing and the links to the data get lost.

**Comment by CEKrause** [comment]
I can't work out how to fix the relative notebook link 'Unknown type' errors. The links are all correct and are working in the VDI, but just not here in git??

**Comment by CEKrause** [comment]
If you open this commit in NBViewer, all the relative links work perfectly?

**Pull request merged**
