### PR TITLE
Added climate driver notebook

### PR DESCRIPTION
**Pull request by MatthewJA**
Added a notebook that estimates climate driver influence on rainfall. I want to use this as a comparison for doing the same thing with waterbodies, since the behaviour of rainfall is better understood than the behaviour of wet surface area.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Comment by MatthewJA** [comment]
Only works on the NCI, since the BOM rainfall grid isn't available on the sandbox.

**Review by CEKrause — CHANGES_REQUESTED** [review]
Few small comments:
- the DEA logo doesn't seem to be loading properly in the document header. Maybe the file path needs to be modified?
- Can you please add in some more code comments to indicate what you are doing in each cell? I pretty much comment every line of code, especially for things being pushed to develop where people unfamiliar with what you're doing will see it. 
- Super cool code workflow being shared here.

**Comment by MatthewJA** [comment]
@CEKrause the logo seems to be working fine when I load this up on Sandbox...
image

**Review by CEKrause — APPROVED** [review]
Woo. Nice additional comments and code doco, thanks.

**Pull request merged**
