### PR TITLE
Add new Collection 3 Fractional Cover notebook to DEA Datasets

### LINKED ISSUE #667: Update DEA_datasets folder to include Fractional Cover notebook
From Issue #615

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
This PR adds a brand new Collection 3 Fractional Cover notebook, explaining how to inspect the available FC products and measurements, how to load data, and a simple best-practice example of analysing the data (including cloud masking from WO):

https://github.com/GeoscienceAustralia/dea-notebooks/blob/c3_dea_datasets/DEA_datasets/DEA_Fractional_Cover.ipynb

The format of the notebook is intended to match the other "DEA *" notebooks in DEA datasets. All content in the intro section is taken directly from CMI.

I'd love a quick review for typos/formatting/usability, but particularly that I've characterised the product and best approaches for loading/analysing it - if you have a chance before Friday that would be amazing!

### Closes issues (optional)
- Closes Issue #667

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [X] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
@fangfy Feel free to have a look too if you have time!

**Comment by robbibt** [comment]
<p>My preference is to not tweak this section - it currently comes directly from CMI and I'd like to keep that the point of truth (we can hassle&nbsp;@LeoLym to make any changes!). I have however included the link, and used FC in the rest of the notebook</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/829/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Updated to just DEA, and removed "data" where applicable". Updated to "missing or invalid"</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/829/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Let's save this for a bulk edit in a future PR - would be easiest to do this in one go and make sure we have everything consistent</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/829/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/829/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Done!</p><p> </p><p>Re "Not sure if it's because of model uncertainties + limitations of training data, and more of limitations in the minimisation... hm", this comes directly from CMI, we should update that if necessary. </p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/829/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Added a sentence describing what users can see in those panels, including cloud</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/829/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Added a code comment</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/829/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Have left "unclear" for now as it's the terminology used in the WO bitmasking notebook, and mirrors the "clear" category in Fmask</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/829/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/829/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/829/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>As discussed, will leave line chart for now and replace with stacked bar chart if we update the notebook to show a more dynamic example</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/829/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
@MatthewJA Updated, thankyou for the review!

**Comment by robbibt** [comment]
@MatthewJA Updated, thankyou for the detailed review!

**Review by MatthewJA — APPROVED** [review]
LGTM

**Pull request merged**
