### PR TITLE
add comments to FC notebook addressing issue #249

### PR DESCRIPTION
**Pull request by BexDunn**
Added the following text to address the issue that external users may not have a clone of the repo:

`This notebook assumes you have cloned the dea-notebooks repository by following the instructions on [DEA notebooks using command line git](https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-command-line-git). If you didn't, you will need to download any scripts that fail in the first cell into your relative directory so that the notebook will have access to those scripts. `

### CODE REVIEW

**Comment by robbibt** [comment]
Yay, that would be a good addition for lots of the notebooks. Can you update:

"If you didn't, you will need to download any scripts that **fail** in the first cell into your relative directory so that the notebook will have access to those scripts."

to:

"If you didn't, you will need to download any scripts that **fails** in the first cell into your relative directory so that the notebook will have access to those scripts."

**Comment by robbibt** [comment]
Actually, small optional suggestion: uses can still get the same effect if they simply download the entire repository using the instructions here (https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-github), and we don't want to scare people away by making think they have to go full-git. I'd update it to something like:

"This notebook assumes you have cloned the latest version of the dea-notebooks repository by following the instructions on [DEA notebooks using command line git](https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-command-line-git) or [DEA notebooks using Github](https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-github). If you didn't, you will need to download any scripts that fail in the first cell into your relative directory so that the notebook will have access to those scripts."

**Comment by robbibt** [comment]
@BexDunn Actually, small optional suggestion: uses can still get the same effect if they simply download the entire repository using the instructions here (https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-github), and we don't want to scare people away by making think they have to go full-git. I'd update it to something like:

"This notebook assumes you have a copy of the latest version of the dea-notebooks repository by following the instructions on [DEA notebooks using command line git](https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-command-line-git) or [DEA notebooks using Github](https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-github). If you don't, you will need to download any scripts that fail in the first cell into your relative directory so that the notebook will have access to those scripts."

**Comment by BexDunn** [comment]
@robbibt have incorporated your suggestions. see what you think? :)

**Comment by BexDunn** [comment]
This notebook assumes you have cloned the dea-notebooks repository by following the instructions on [DEA notebooks using command line git](https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-command-line-git) or [DEA notebooks using Github](https://github.com/GeoscienceAustralia/dea-notebooks#dea-notebooks-using-github). If you didn't, you will need to download any scripts that fail in the first cell into your relative directory so that the notebook will have access to those scripts. `"../"` means the directory above the directory you are working in, and `"./"` means the current directory.

**Pull request merged**
