### PR TITLE
Update Exporting GeoTIFF notebook to use `write_cog`

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
Code in this repo needs to be updated to use the newer `write_cog` function instead of the deprecated `write_geotiff` (e.g. #586). This PR starts this process by updating the "Write_GeoTIFF" notebook to use `write_cog`, so at least we have some nice examples to point new users to.

Have also included two brief sections on:
1. Supplying custom `rasterio.open` kwargs like nodata
2. Using `write_cog` with `dask` arrays

Still to do (in a second PR): replace all instances of `write_geotiff` in other notebooks with `write_cog`.

### Closes issues (optional)
Partially contributes to #586

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
@Kirill888 No need for a detailed review, but just bringing to your attention in case anything about `write_cog` is clearly incorrect

**Comment by Kirill888** [comment]
This looks good, thanks. Only other thing maybe is to talk about exporting `float32` data with `nan` that should not have `nodata` set at all. To achieve this one has to make sure that `nodata` attribute is not set on the array, there is no way to overwrite `nodata` into "nothing", so one has to `xx.attrs.pop('nodata', 0)` if they want to generate COG without `nodata` set. 

Other comment would be around `.isel(time=1)`, so this saves the second slice, but can be confused for saving "first" slice instead. So maybe `.isel(time=0)` is more copy-paste friendly, and if first slice is too boring maybe pick something other than `1`, so that it's more obvious that this needs editing after pasting.

**Comment by robbibt** [comment]
Thanks @Kirill888, those are great suggestions. I'm just starting to write up a bit on your first point re nodata and float arrays... did you have a particular scenario in mind for this? Just thinking that it's still technically possible to have a float array with `NaN` values but also a nodata attribute, for example, you mask out clouds with `NaN`, but there are still -999 values in the data that haven't been replaced (so the attribute is still valid)?. I also was writing up the example based on when you've used `mask_invalid_data` to set nodata values to `NaN`, but it seems that function already drops the `nodata` attribute automatically so the user doesn't need to do it themselves.

**Comment by Kirill888** [comment]
@robbibt I think someone Bex collaborates with had this problem, one of index computations utilities didn't drop `nodata` flag from output and they were confused as to why `nodata=0` was set on the output file. It's really a limitation, a gotcha, of the API, one can replace `nodata` with some other value at call time but one can not request "to not write one at all", since if you just supply `nodata=None` this really means "use nodata flag on the input and if set write that to file" rather than "do not set nodata flag on the output image at all regardless of what input is".

Regarding floats, yes you can have both NaN and some other special value also, but I would say this should be discouraged, whole idea of `nodata` is to emulate NaN for data stored in integer formats. If you use float data, you have NaN, so use that.

**Review by BexDunn — APPROVED** [review]
Hey Robbi. The bit on nodata looks both good and useful to me, and I think it's handy to have the commentary on dask as well. Nice work.

**Pull request merged**
