### PR TITLE
Notebook wofs bitmask

### PR DESCRIPTION
**Pull request by bellemae**
_Note: checklist below only relevant if committing to the [`develop`](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop) branch:_

### Proposed changes
This is a notebook to explain the structure of water observation feature layers WOFLs, and how to use  them for masking.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
@erialC-P @bellemae The `wofs_fuser` function has been added to `dea_datahandling`, I think `wofls_fuser` could be as well! https://github.com/GeoscienceAustralia/dea-notebooks/blob/develop/Scripts/dea_datahandling.py#L464

**Comment by erialC-P** [comment]
In the Introduction, you also mentioned that more options to explore the data would be offered at the end of the notebook but I think these still need to be added (or you can edit your original comment and delete this suggestion!)

**Comment by katedugdale** [comment]
This is an informative notebook, I felt like I could finally understand what a WOFL is after going through it a few times. One thing that I thought would make it easier for first timers to understand is  to add a little bit about what is meant by 'Features' in the very first section:

"Individual water classified images are called Water Observation Feature Layers (WOFLs), where the feature could be something like mountain shadow, ocean, surface water or wet vegetation....."

If the reader has in mind what the feature could be from the start, it makes it a bit easier to follow on the first read-through.

**Comment by robbibt** [comment]
@erialC-P I can't seem to accept and merge this PR... I think you might need to do the final step!

**Pull request merged**
