### PR TITLE
Intertidal exposure

### PR DESCRIPTION
**Pull request by erialC-P**
### Proposed changes
This PR adds a new notebook to the Real_world_examples suite and demonstrates customisation options that are available when undertaking intertidal exposure analysis.
The notebook is a bit slow to run in some places, with the whole runtime being approximately 6 - 10 minutes. Much of this speed is accounted for in the use of the exposure function which runs very high resolution tidal modelling in the background. However, some of the lagginess may be related to the use of animations/gifs in the notebook.

### Checklist 
(Replace `[ ]` with `[x]` to check off)

- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x ] Remove any unused Python packages from `Load packages`
- [x ] Remove any unused/empty code cells
- [x ] Remove any guidance cells (e.g. `General advice`)
- [x ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x ] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://knowledge.dea.ga.gov.au/genindex/), and re-use tags if possible)
- [x ] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with
- [x ] Check for any spelling mistakes using the DEA Sandbox's built-in spellchecker (double click on markdown cells then right-click on pink highlighted words). For example:

sandbox_spellchecker

### CODE REVIEW

**Comment by robbibt** [comment]
@erialC-P  I've just done a quick skim through for now, but this is fantastic... feels almost like an interactive/runnable version of a scientific paper, which is really neat and perfect for a Real world example I think! 🤩 

I've suggested some small changes - I might jump into the branch and make some minor code suggestions at a later point too. For now, my only "more general" comment would be to go through and run either Black or YAPF code formatting on all the code cells so everything is nice and consistent - I think some got missed earlier.

**Comment by erialC-P** [comment]
<p>You're right. This was legacy code. Deleted :)</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1261/discussion/#comment-2285276581'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by erialC-P** [comment]
<p>On further testing, it's totally redundant as it doesn't work. I was trying to automatically restart the kernel following the pip install. Will test whether a restart is even required.</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1261/discussion/#comment-2285276587'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by erialC-P** [comment]
<p>fixed :)</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1261/discussion/#comment-2285276601'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by erialC-P** [comment]
<p>great suggestion!</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1261/discussion/#comment-2285276606'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by erialC-P** [comment]
<p>good point. I've removed that line and updated figure outputs into the R_W_E folder</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1261/discussion/#comment-2285276592'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by erialC-P** [comment]
<p>Yep - since found that little bug too. Updated to os.getcwd() which should set all figure outputs to the R_W_E folder alongside the notebook</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1261/discussion/#comment-2285276626'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by erialC-P** [comment]
<p>Yeah, definitely open to that! Wasn't sure if this figure style was a bit niche to this application but a func would allow it to be very customisable!</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1261/discussion/#comment-2285276633'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by erialC-P** [comment]
<p>Yep! I agree that this is a good idea. Testing with a 2 H frequency gives results consistent with the notebook narrative so I'll reduce the frequency and add a note above with advice about freq selection.</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1261/discussion/#comment-2285276637'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by erialC-P** [comment]
<p>Nope! More legacy code :D</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1261/discussion/#comment-2285276654'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by erialC-P** [comment]
<p>Thanks! It tells a pretty cool story :)</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1261/discussion/#comment-2285276666'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by erialC-P** [comment]
<p>Done :)</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1261/discussion/#comment-2285276611'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by erialC-P** [comment]
<p>Actually...with a fresh kernel, it turns out that I did need to keep this line. I wonder if it's because it's a non-standard package...?</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1261/discussion/#comment-2285276581'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by robbibt — APPROVED** [review]
Amazing!

**Pull request merged**
