### PR TITLE
New `xr_pansharpen` function and notebook for pansharpening Landsat

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
This PR adds a new function to `dea_tools` called `xr_pansharpen` that allows users to apply several popular pansharpening transforms to Landsat data, including:

* **Brovey pansharpening ("brovey")**: a simple algorithm designed to optimise visual contrast at both ends of the satellite imagery's histogram. The approach multiplies each lower resolution multispectral band by the ratio of the higher resolution panchromatic band, divided by the sum of all three multispectral bands.
* **Simple mean ("simple mean"):** Takes the average of each low resolution multispectral band and the panchromatic band
* **ESRI ("esri"):** Takes the mean of the all low resolution multispectral bands, then subtracts this from the higher panchromatic band to produce an "adjustment factor" which is then added back to each band
* **Hue Saturation Value ("hsv"):** Converts low resolution image data from RGB to HSV colour space, where "V" represents "Value", or the relative lightness or darkness of the image. This band is replaced with the higher resolution panchromatic band, then converted back to the original RGB colour space.
* **Principal Components Analysis ("pca"):** transforms low resolution original data into its principal components, then substitutes the first principal component with the higher resolution panchromatic band.

The func can be applied to DEA Landsat datasets containing one or more timesteps.

Have updated the previous Pan-sharpening with Brovey notebook to use the new function, including an advanced section demonstrating a possible way to evaluate the different pansharpening transforms.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
Hey @BexDunn @geoscience-aman @margaretharrison @erialC-P @tebadi, @vnewey, if any of you had some spare time to give this PR a quick review that would be amazing - once this is merged I'm hoping to do an official 0.3.0 release of `dea_tools` as I think we've got plenty of nice new things in there to warrant a 0.X.0 version!

**Comment by robbibt** [comment]
@sixy6e I think you worked on the original notebook with @GypsyBojangles - let me know if you have any thoughts/suggestions!

**Review by treefern — APPROVED** [review]

**Comment by robbibt** [comment]
<p>Great catch, fixed!</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/994/discussion/#comment-1401239004'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Yep, good idea. Have updated to:</p><p> </p><p>"Satellite instruments are designed to capture images at a certain signal-to-noise ratio. Compared to multispectral satellite bands that cover multiple narrow portions of the electromagnetic spectrum, a panchromatic satellite band covers a wide spectral range that overlaps with multiple multispectral bands. This wider spectral range allows panchromatic bands to receive more energy per pixel than the multispectral bands. This means that compared to multispectral bands, panchromatic bands can be collected at a higher spatial resolution while still meeting the satellite instrument's signal-to-noise threshold."</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/994/discussion/#comment-1401272675'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Agree, this is a legacy of the old notebook that applied only Brovey. Have removed</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/994/discussion/#comment-1401272757'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/994/discussion/#comment-1401272876'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Also caught by @treefern, thanks!</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/994/discussion/#comment-1401272830'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Yep good ideas, have added refs and have added a link to the evaluation section</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/994/discussion/#comment-1401272926'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Simple mean and ESRI are simple vectorised array operations and can be applied to the entire dataset in one function call  - HSV and PCA need to be applied to each timestep individually. But the print statement here is confusing, I think I'll get rid of it because it doesn't really matter to end users how it works under the hood</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/994/discussion/#comment-1401272981'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Yeah I don't think I finished this section - fixed!</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/994/discussion/#comment-1401273131'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
<p>Great idea! Have implemented this</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/994/discussion/#comment-1401273093'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by robbibt** [comment]
Thanks so much @treefern and @geoscience-aman - lots of great improvements there! Have implemented them all, and if you're happy I'll merge this PR after the tests run 😃

**Review by geoscience-aman — APPROVED** [review]

**Pull request merged**
