### PR TITLE
Add first set of basic Testbook tests to DEA Notebooks

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
Work-in-progress PR to capture progress adding tests to the `nbtests` branch.

### Closes issues (optional)
- Closes ##507

### CODE REVIEW

**Comment by robbibt** [comment]
Currently having issues with testing notebooks that include a relative link to data from the `Supplementary_data` directory, e.g.: 
image

**Comment by robbibt** [comment]
Datacube products to index:

* [ ] ls7_nbart_geomedian_annual
* [ ] ls8_nbart_geomedian_annual
* [ ] s2a_ard_granule
* [ ] s2b_ard_granule
* [ ] ga_ls5t_ard_3
* [ ] ga_ls7e_ard_3
* [ ] ga_ls8c_ard_3
* [ ] wofs_annual_summary

**Comment by robbibt** [comment]
URIs required for the `04_Loading_data.ipynb` notebook:

ls7_nbart_geomedian_annual:
`['s3://dea-public-data/geomedian-australia/v2.1.0/L7/x_20/y_-32/2015/01/01/ls7_gm_nbart_20_-32_20150101.yaml']`

ls8_nbart_geomedian_annual:
```
['s3://dea-public-data/geomedian-australia/v2.1.0/L8/x_20/y_-32/2014/01/01/ls8_gm_nbart_20_-32_20140101.yaml',
 's3://dea-public-data/geomedian-australia/v2.1.0/L8/x_20/y_-32/2015/01/01/ls8_gm_nbart_20_-32_20150101.yaml',
 's3://dea-public-data/geomedian-australia/v2.1.0/L8/x_20/y_-32/2017/01/01/ls8_gm_nbart_20_-32_20170101.yaml',
 's3://dea-public-data/geomedian-australia/v2.1.0/L8/x_20/y_-32/2016/01/01/ls8_gm_nbart_20_-32_20160101.yaml',
 's3://dea-public-data/geomedian-australia/v2.1.0/L8/x_20/y_-32/2013/01/01/ls8_gm_nbart_20_-32_20130101.yaml']
```


Extracted using:
```
query = {"x": (153.3, 153.4),
         "y": (-27.5, -27.6),
         "time": ("2013", "2017")}
dss = dc.find_datasets(product="ls8_nbart_geomedian_annual", **query)
[i.uris[0] for i in dss]
```

**Comment by robbibt** [comment]
Just documenting the errors we hit in indexing data for `06_Basic_analysis.ipynb` so we don't lose Slack memory:

```
Added 0 Datasets, Failed 2 Datasets
ERROR:root:Error: s3://dea-public-data/baseline/s2a_ard_granule/2018-10-09/S2A_OPER_MSI_ARD_TL_EPAE_20181009T021157_A017216_T55LBD_N02.06/eo3-ARD-METADATA.odc-metadata.yaml, Dataset metadata did not match product signature.
```

**Review by BexDunn — APPROVED** [review]
Nice work @robbibt . We can add the rest as we go, good to get some done and the rest can follow.

**Pull request merged**
