### PR TITLE
Zhihuang modis

### PR DESCRIPTION
**Pull request by zxh547**
### Proposed changes

I would like to add the following four notebooks using the DEA's MODIS database:
1. An introduction to the DEA's MODIS ocean colour and SST dataset.
2. A real world example of how to charaterise the SST properties of a selected Australian Marine Park.
3. A real world example of how to characterise the cholorophyll-a properties of a selected Australian Marine Park.
4. A real world example of how to identify and characterise marine heat waves of a selected Australian Marine Park.

These notebooks will help general users access the newly acquired MODIS database in DEA and gain a basic understanding of the products available in this database. They will also demonstrate DEA's capabilities in marine remote sensing, especially to the marine park managers in the environmental department, one of our key stakeholders. 

### Closes issues (optional)
- Closes Issue #000
- Closes Issue #000

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [ ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended). Note that I could not find such options in VDI jupyter notebook.
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed) Note that as the MODIS database is only in NCI, testing in DEA Sandbox is not possible.
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
Hi @zxh547, thanks for this! Just before I jump in and review, a more general question: are the MODIS products currently available in the public/default DEA database?

If they aren't, we might need to think strategically about the best way to deal with this PR and others like it that use non-standard/default data or products. Currently, the public facing branches of the DEA Notebooks repo (e.g. `develop`, `master`) contain only notebooks and code for analysing products within the default set of products. This is important because notebooks in the `Beginners_guide`, `DEA_datasets`, `Frequently_used_code` and `Real_world_examples` folders also form part of the [official DEA documentation here](https://docs.dea.ga.gov.au/). Publishing notebooks that use non-standard products in the user guide is tricky because DEA doesn't "officially" support these products. 

A potential solution would be to move the MODIS notebooks from their current location in `Real_world_examples` to a new folder (e.g. "MODIS") inside [the `Scientific_workflows` folder](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop/Scientific_workflows). This folder is designed to cater for workflows that use non-default datasources, or that aren't completely reproducible using default DEA products and data. The notebooks would then be easily accessible via Github and for anyone who clones the repository, and we could move them across to the more official `Real_world_examples` and include them in the user guide as soon as the MODIS products are officially added as DEA products.

I'll give some further thought to this and see if I can think of any other good solutions... this is definitely something we're going to come across in the future as we start to experiment with new potential DEA data sources, so it will be good to come up with a nice approach for this.

**Comment by zxh547** [comment]
Hi Robbi,

MODIS products are currently only in the development database. I am not sure how to proceed with these four MODIS notebooks. All I can do is to make them "publication" ready. But where and when to "publish" them, as you suggested, remain to be discussed and determined.

Hi Steve, would you be able to give us some indications of the next steps?

Happy to discuss.

Regards

Zhi

________________________________

**Comment by zxh547** [comment]
I think in the scientific workflows folder makes sense. There has been not bandwidth within the current priorities in Core to make the MODIS feed from CSIRO a production database.

A paragraph noting the developmental nature of the database in the notebooks would make this clear too.

If/When we can get a production version moving , we can always do as Robbi suggests and transition them to an official DEA section.

S

**Comment by zxh547** [comment]
Hi Steve,

Agreed. I am happy for all four notebooks to be moved to the "Scientific_workflows" folder for the time being.

Robbi, do you want me to do this on my end?

Regards

Zhi

________________________________
From: Sagar Stephen <Stephen.Sagar@ga.gov.au>
Sent: Thursday, 11 June 2020 10:37 AM
To: Huang Zhi <Zhi.Huang@ga.gov.au>; GeoscienceAustralia/dea-notebooks <reply@reply.github.com>
Cc: BishopTaylor Robbi <Robbi.BishopTaylor@ga.gov.au>
Subject: RE: [GeoscienceAustralia/dea-notebooks] Zhihuang modis (#584) [SEC=OFFICIAL]


I think in the scientific workflows folder makes sense. There has been not bandwidth within the current priorities in Core to make the MODIS feed from CSIRO a production database.



A paragraph noting the developmental nature of the database in the notebooks would make this clear too.



If/When we can get a production version moving , we can always do as Robbi suggests and transition them to an official DEA section.



S

**Comment by CEKrause** [comment]
@robbibt the notebooks contain information about the non-standard nature of the data they are using. The metadata at the top of the notebook outlines that it's in a special standalone database, and the notebooks also contain the information needed to connect to that db. 
I think having them in `scientific_workflows` sounds like a good compromise, because we don't have to add them to the readme to render to the official doco (like we do with DEA Waterbodies).

**Comment by robbibt** [comment]
Yep OK, I think that sounds good!

@zxh547 , do you want to move the notebooks into a new folder inside Scientific Workflows? e.g. `Scientific_workflows/MODIS` or something like that

(or let me know and I can try doing it when I get some free time!)

**Comment by zxh547** [comment]
Hi Robbi,

Yes, I can do that.

Thanks

Zhi

**Comment by zxh547** [comment]
Hi Robbi,

I just moved the four MODIS notebooks to scientific_workflows/MODIS. Let me know if there is any further issues.

Regards

Zhi

**Comment by zxh547** [comment]
Hi Robbi,

I forgot to pull the update from the develop branch before committing my changes to the zhihuang_MODIS branch. You can see now the zhihuang_MODIS is 3 commits ahead but 7 commits behind the develop branch. When you merge, can you please just merge the four MODIS notebooks to Scientific_workflows?

Thanks

Zhi

**Comment by zxh547** [comment]
Thank you Robbi and Claire for the help. The MODIS notebooks now appear in the develop branch!

Regards

Zhi

**Comment by robbibt** [comment]
No problem, they look great! You should post a link on "look-i-did-a-thing"!

**Comment by robbibt** [comment]
@zxh547  No problem, they look great! You should post a link on "look-i-did-a-thing"!

**Pull request merged**
