### PR TITLE
Update ARD_overpass_predictor.ipynb

### PR DESCRIPTION
**Pull request by Eric-git-999**
### Proposed changes
FIx start time for "timedummy" function, update from 2019 to 2020. This function orders dates, and needs to overlap the overpass predictions. Also Increase the number of iterations of "timedummy" from 300 to 500.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by BexDunn** [comment]
Hey Eric! What does updating this do?

**Comment by Eric-git-999** [comment]
Hey Bex, just a thing I overlooked. The "timedummy" is a list of dates, and I had them starting in 2019 (from when I first started working on this Notebook). 
If you are adding a start date, now in 2021, this may be later than the end of the "timedummy" if it starts in 2019.

I will look at a more elegant fix, something like grabbing the current month / year as the start point of the timedummy would be ideal, but in the mean time this update will keep it working properly :)

**Comment by Eric-git-999** [comment]
Ok, fixed up properly now. "timedummy" grabs the current month and year :)

**Review by BexDunn — APPROVED** [review]
looks good

**Pull request merged**
