### PR TITLE
Turbidity_Animated_Timeseries_notebook

### PR DESCRIPTION
**Pull request by Joram95**
Proposed real world example notebook "Turbidity_animated_timeseries" created by Joram Downes

### Proposed changes
This notebook allows the user to create a time series animation depicting a turbidity plume at the Murray Mouth and the surrounding coastline. The animations contrast Sentinel-2 imagery taken from early-2022 to mid-2023; this coincides with the flood of a generation, peaking in mid-January 2023, leading to a stark decline in water quality within the vicinity. This example demonstrates how to: 
- Load Sentinel-2 data
- Compute a turbidity and water indices (NDTI, NDWI)
- Mask pixels which contain land and cloud
- Create time series animations
- Visualise changes in turbidity throughout a floodwater discharge event

### Closes issues (optional)
- Closes Issue #000
- Closes Issue #000

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [ ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [ ] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by erialC-P** [comment]
Hey Joram!
Thank you so much for the addition of this AWESOME notebook to the collection. I'm looking at your PR this week and will make a couple of updates to the dea_tools module so that your notebook here can really pop! In the meantime, I just wanted to let you know that I'm looking at this PR and will approve and merge it asap!

**Comment by Joram95** [comment]
Thanks Claire,Good luck and happy coding!FYI I’m leaving the country tomorrow and won’t have my laptop so I might not be able to assist until the 3rd of July. I will be able to answer emails 😊Cheers,Joram   From: ClairePSent: Thursday, 15 June 2023 4:36 PMTo: GeoscienceAustralia/dea-notebooksCc: spatial_coastal_joram; AuthorSubject: Re: [GeoscienceAustralia/dea-notebooks] Turbidity_Animated_Timeseries_notebook (PR #1073) Hey Joram!Thank you so much for the addition of this AWESOME notebook to the collection. I'm looking at your PR this week and will make a couple of updates to the dea_tools module so that your notebook here can really pop! In the meantime, I just wanted to let you know that I'm looking at this PR and will approve and merge it asap!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Joram95** [comment]
Thanks Claire,
Good luck and happy coding!
FYI I’m leaving the country tomorrow and won’t have my laptop so I might not be able to assist until the 3rd of July. I will be able to answer emails 😊
Cheers

**Review by erialC-P — APPROVED** [review]
Hey Joram,
Thanks for your hard work in adding this excellent notebook to the DEA-notebooks repo!
I made a small series of changes that are incorporated into my commit of the notebook to your branch. 
I made some minor changes to simplify your two masking steps. The cloud masking outputs are unchanged. I updated the land masking to make it dynamically mask each time step against itself which will hopefully account for changes in tide and inland flooding as relevant at other locations across Australia.
This PR also motivated an update to the dea_tools repo meaning your notebook now includes a direct calculation of NDTI and your subplots can now be labelled with their timesteps to support users to select the images for their animations.
I hope you're supportive of these changes. Feel free to recommend reverting to the original code, especially in the case of the masking. Otherwise, this notebook is a great addition to the resources in the repo and is ready to be added once the related dea_tools PR is approved. (I'll jump in and finalise the approval of this PR once the other is approved, unless I hear from you first!)
Thanks again!

**Comment by Joram95** [comment]
That all sounds great! I think every change you have made has enhanced the code. I look forward to seeing it up on the sandbox.
Many Thanks 👍

**Comment by robbibt** [comment]
Yep, had a quick look too and this looks awesome - fantastic work @Joram95 and great changes @erialC-P!

I have a few tiny suggestions (mainly around consistency with other notebooks, and a change to reduce the file size of the notebook) so I'll do a super quick review too once Claire's stuff is all integrated 😃

**Pull request merged**
