### PR TITLE
New notebook demonstrating pixel edge polygonisation

### PR DESCRIPTION
**Pull request by BexDunn**
### Proposed changes
New notebook demonstrating creating pixel boundaries as a vector files, for Landsat and Sentinel 2. Useful for Melbourne Water, ARI applications - happy to move to Scientific Workflows if you'd rather, but potentially also useful for drone imagery comparison - I believe it's multipurposeness means it should be good in Frequently used code. 

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by BexDunn** [comment]
> This looks great @BexDunn. I have a couple of small suggestions:
> 
> * can you keep the notebook outputs? It makes it easier to see what each cell is doing, particularly for example code like in `Frequently_used_code`
> * You can probably delete: 'Use standard import commands; some are shown below. Begin with any iPython magic commands, followed by standard Python packages, then any additional functionality you need from the Scripts directory.'. I think it's just a template comment, rather than a bit to publish?
> 
> Otherwise, it looks good!

Generally I would keep the outputs, except now it's a standard part of our PR that we dont...

**Comment by CEKrause** [comment]
I just had a quick look through the other frequently used code notebooks, and they seem to have outputs in the repo?

**Comment by CEKrause** [comment]
Wasn't removing the outputs just something you and Emma were doing? Maybe?

**Comment by BexDunn** [comment]
Cool, will re-run the thing.

**Comment by robbibt** [comment]
This looks awesome! Definitely a good one for `Frequently_used_code`. Let me know when you've pushed changes and I'll quickly review!

**Comment by BexDunn** [comment]
> This looks awesome! Definitely a good one for `Frequently_used_code`. Let me know when you've pushed changes and I'll quickly review!

updated, potentially too late this evening :)

**Comment by robbibt** [comment]
Looks great, I just made some minor formatting changes, as well as reducing the study area size so the notebook runs quicker.

My only slightly larger comment would be that it would be great to actually plot up some of the resulting shapefile results over the top of the `xarray` rasters directly inside the notebook, or at least include a screenshot of what the end result should look like so users don't necessarily need to download all the outputs and compare them in a GIS to see it. E.g. I think something like this both looks cool and really gets the point across about what the notebook produces:

image

The problem at the moment is that the area in the queries is too large to meaningfully plot the outputs... perhaps you could choose a super tiny area for each example (e.g. 20 x 20 pixels)?

**Comment by BexDunn** [comment]
Those are excellent suggestions @robbibt - I'll cut down the size and have a crack at displaying them. Did you use the rgb with poly tools to display?

**Pull request merged**
