### PR TITLE
Scalable ML on the ODC

### PR DESCRIPTION
**Pull request by cbur24**
### Proposed changes
Porting over the Scalable Machine Learning notebook series from DE Africa.  During reviews, if you find typos and/or small changes that need doing, please push fixes back to the PR rather than simply commenting as I won't have time make every small change. 

As well as the notebooks, this PR also includes a new module called `dea_segmentation` that conducts parallel, tiled image segmentation.  There are supplementary figures also included.

The reason for two `readme` files is so the Sandbox/VDI user can have a rendered readme to guide them through the process (the read.md doesn't render in Jupyter Lab), and to acknowledge that some users might discover this series in the sandbox file browser rather than through github.

There are currently two sets of training labels in the `data/` folder: `crop_training.geojson` (2000+ polygons) and `crop_training_WA.geojson` (430 polygons).  The notebooks currently uses the WA dataset (which is a subset of `crop_training`) as it runs a lot faster. But the results are nicer using the whole dataset because the 'crop' labels are better distributed, and the user can then classify any region in Australia.  But with only two cpus on the default sandbox it takes >25 mins to gather the training data from the datacube (compared to 6 mins with the WA subset).    

I have not tested this on NCI as I am no longer set-up to run things since the Gadi transition

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [X] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Review by erialC-P — APPROVED** [review]
Really great set of notebooks with high value to the dea-notebooks repository

**Comment by robbibt** [comment]
I'd love to go through these but don't have time this week... If we could leave this open until next week that would be fantastic!

**Comment by cbur24** [comment]
> 
> 
> I'd love to go through these but don't have time this week... If we could leave this open until next week that would be fantastic!

Yes of course, @robbibt . Happy to leave it open until everyone is satisfied - there is a lot of material here so worth a thorough review process.

**Review by s-m-t-c — APPROVED** [review]
Read and ran everything through, excellent work. 

I changed some plot ordering / labeling for clarity.
Some  things such as the CPU calculation don't work on the NCI. 

```
ncpus=round(get_cpu_quota())
print('ncpus = '+str(ncpus))
```

**Comment by cbur24** [comment]
@robbibt I'm planning on merging this one today as Sean and I would like to use these notebooks for a live demo next week. If you don't have to time to review today then is it fine if we merge them? When you get a chance to review we can make changes through a new PR?

**Comment by robbibt** [comment]
@cbur24 I can review today! Will have a look now

**Review by robbibt — APPROVED** [review]
This is an incredible resource - amazing work! I want to go through this slowly in more detail for my own benefit later on, but for now I've just made some minor consistency updates (e.g. PEP8 formatting) and added the notebooks to the readme.rst so hopefully they show up in the user guide. Happy for this to be merged! 🚀

**Comment by cbur24** [comment]
Thanks to everyone for the thorough reviews

**Pull request merged**
