### PR TITLE
Fixed several links after running link checker tools on the site

### PR DESCRIPTION
**Pull request by benji-glitsos-ga**
### Proposed changes
Fixed several links after running link checker tools on the site

### Closes issues (optional)
None

### Checklist (replace `[ ]` with `[x]` to check off)
- [ ] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [ ] Remove any unused Python packages from `Load packages`
- [ ] Remove any unused/empty code cells
- [ ] Remove any guidance cells (e.g. `General advice`)
- [ ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [ ] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex/), and re-use tags if possible)
- [ ] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
Hey @benjamin-glitsos, the reason for those relative links to scripts and notebooks is so that users can click through them on the DEA Sandbox and have the coresponding script open up to access the code. It's pretty important, particularly for notebooks that form a set that are run in order (e.g. "Click to launch Notebook 2 of 5" etc).

Is there any way we can continue to use relative links in the Notebooks and still have them load correctly in Knowledge Hub? That used to work in the original DEA Docs.

**Comment by benji-glitsos-ga** [comment]
Hi Robbi, I'll try to find a solution. The problem is that the relative links weren't working when rendered on the Knowledge Hub site.

**Comment by robbibt** [comment]
Thanks @benjamin-glitsos! I've just realised that most of the relative links to notebooks and scripts were actually removed in the previous PR, not this one... we'll probably need to revert those changes to restore them so they work correctly for our Sandbox users, so some way of dealing with relative links in KH would be ideal. 

I wonder if this could be dealt with via yet more redirects? e.g. updating the auto-resolved URL with one that points to the correct KH location...

**Review by robbibt — APPROVED** [review]
Don't want to hold up your work so approving for now, but noting that we'll probably need to revert back to relative links in DEA Notebooks so that they work correctly for our Sandbox users.

**Pull request closed without merging**
