### PR TITLE
Geomedian filmstrip plots of change through time notebook

### PR DESCRIPTION
**Pull request by robbibt**
### Proposed changes
Added a new notebook (based on an old notebook) that allows a user to select an area from an interactive map, and generate a geomedian filmstrip plot that highlights change through time.

This uses dask to improve performance; this may work on the NCI but for now I've marked it as a Sandbox-only notebook.

For coastal applications, users can specify a specific portion of the tidal range to generate geomedians from (e.g. low tide, high tide).

filmstrip_example

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by caitlinadams** [comment]
This looks like a super cool notebook! I was wondering whether it belongs more in Frequently_used_code though? While you've got a good background section, there isn't much analysis/commentary about how the film-strip supports a real-world decision/action. Perhaps adding some of this context would round it out as a Real_world_examples notebook? It might also benefit from a title that ties it more to the real world context, rather than the specific analysis, but that doesn't currently hold true for all real world notebooks either (so, up to you).

**Comment by robbibt** [comment]
@caitlinadams It's a tricky one! I think I see the notebook fitting in `Real world examples` because it's designed as a functional tool for obtaining real-world insights from satellite data... whereas `Frequently used notebooks` provide minimum viable code for performing common tasks. This tool is something that's come up frequently from various stakeholders as something they would find useful, so it's quite similar to Katie's inundation notebook in that way. The code in this one is also all locked up inside the "app" function to make it easier to use, while `Frequently used notebooks` generally walk through the different steps in a bit more detail, maybe? 

To address this a bit I have now added some extra interpretation markdown at the end of the notebook which provides some extra info about the kinds of insights the filmstrip plots can help produce, and also the "Next steps" section which we have in the other `Real world examples notebooks`.

**Comment by robbibt** [comment]
The title could definitely be improved... even a simple change to something like `Analysing change through time using filmstrip plots" would help shift the focus onto being able to study change vs. the specific technique

**Comment by robbibt** [comment]
@BexDunn I've just added this to make the load and status a bit clearer:

image

image

**Comment by BexDunn** [comment]
> @BexDunn I've just added this to make the load and status a bit clearer:
> 
> image
> 
> image

Looks good to me, do you want me to squash and merge or do you want to wait for other reviews/ change the title/ etc?

**Comment by robbibt** [comment]
@BexDunn Sean wanted to have a look at it first, so maybe mark as "accepted" so it knows I addressed the requested changes, but leave it un-merged?

**Pull request merged**
