### PR TITLE
Intro to dea

### PR DESCRIPTION
**Pull request by erialC-P**
_Note: checklist below only relevant if committing to the [`develop`](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop) branch:_

### Proposed changes
First draft of an Introduction to DEA notebook

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by erialC-P** [comment]
This is an incomplete first draft of an Intro to DEA notebook for the Beginners_guide. I'd love some advice to get the geolocating and xarray sections completed. I'm very happy for suggestions, comments, revisions, contributions etc

**Comment by robbibt** [comment]
@erialC-P I just did a quick tidy of the branch to remove all new notebooks except the one that's specific to the pull request (this will reduce the likelihood of merge conflicts in the future).

Before you do any more work, please check out this branch and run `git pull` to get the latest version!

**Comment by erialC-P** [comment]
Note to self: add section on nbar and nbart (and pixel quality?)

**Comment by erialC-P** [comment]
This notebook still needs some re-formatting but as there will likely be some content changes/updates I will kill two birds with one stone. I'd really appreciate some feedback on the content. This notebook is a beginners first exposure to the DEA and how it's built etc. This is the precursor notebook to products and measurements as well as loading data so it's meant to have the foundations to understand those notebooks whilst hopefully not being too overwhelming. However, it's very texty and code-less. I have included it in this notebook because I couldn't find it all summarised elsewhere but I'm happy to move this to the docs or something if that is a better option.

**Comment by robbibt** [comment]
@caitlinadams @erialC-P I've made some edits above! Biggest change was adding a visualisation and extra info about NBAR(T) to help give users some help choosing between them. I've also added a new "Derived products" section, and slightly re-written some of the surface reflectance section. I think we're getting pretty close now!

**Comment by erialC-P** [comment]
@caitlinadams and @robbibt, this notebook reads pretty well now. Thank you very much for your reviews! I can't think of any changes to make. Are you both happy to approve?

**Comment by robbibt** [comment]
I'm happy for it to be approved. @caitlinadams?

**Pull request merged**
