### PR TITLE
adding the inundation notebook to the real world examples folder

### PR DESCRIPTION
**Pull request by katedugdale**
_Note: checklist below only relevant if committing to the [`develop`](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop) branch:_

### Proposed changes
Adding the inundation mapping notebook to the real world examples folder
### Closes issues (optional)
none

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [X] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by katedugdale** [comment]
Great, thanks so much Caitlin I will update with all your suggestions and then do a draft pull request again. Yes, the Water Data Online information is publically available and we are currently working on incorporating a widget so the user can directly select a gauge off a map rather than having to go to the website and get it themselves. However, I don’t know how long this will take so in the meantime I will follow your suggestion for adding the csv file to the Supplementary_data folder. I will let you know when I am ready to update it with the mapping widget.

Thank you very much!

Katey

**Comment by caitlinadams** [comment]
That's great to hear, thanks Katey! Also, you can keep this PR open and when you make and push more commits from your branch, they'll just be added to this PR.

Sounds like a really interesting idea about the widget! It's no problem if that takes some time to implement.

**Comment by katedugdale** [comment]
Hi Caitlin, thanks for your suggestions, I agree it is quite hard to go to the site and download the correct csv file, so I have updated this part with a map widget that scrapes the correct data from the Water Data Online website, and I’ve automated the lat and lon selection as per your suggestion as well. I decided to keep the buffer in meters as I think that would be more accessible for most people. I’ve done the commit 2 days ago as updating the inundation notebook with a map and improved mark downs<https://github.com/GeoscienceAustralia/dea-notebooks/commit/ed8b7c3be4da1259ecbaa5c07d14b4b57aba6355>

Let me know if you have any other suggestions for this draft pull, I’m really keen to get it published on the sandbox!

Katey

**Comment by robbibt** [comment]
Hey @katedugdale, this is a really fantastic notebook! I've gone through it and made a few changes to improve usability:

1. Added in a step that filters the gauge station data to only stations that have data. This makes selecting gauges using the map easier because every gauge will give a valid result
2. Made the interactive map center over a nice example gauge (Murray bend) so hopefully users will click on that and get a good result first up
3. Simplified the final figure to have just two panels, because the previous one duplicated the main figure 
4. I've altered the final flooding frequency cell to use `masking.make_mask(clear_specified_passes, wet=True).sum(dim='time')` to identify water. Previously it was identifying water using the WOFLs bit flag == 128, but using `make_mask` is a bit safer as it will include all water regardless of the specific flag.
5. Added tags and the "Additional info" cell

To me it looks like you've addressed all of @caitlinadams 's comments above, so I'd be happy to accept this and merge it into the repo as soon as you mark it as "ready to review"!

**Comment by katedugdale** [comment]
Thanks Robbi! OK, I’ve marked this notebook as “Ready for Review”!

Katey

**Comment by caitlinadams** [comment]
This is looking really good! I have a few minor changes that I was hoping you could add, but other than that, I think it's ready to go.

- The BOM UI looks great! Is it possible to add a y-axis label to the plot that it outputs (including units if any)? "Timestamp" is a reasonable x-axis label, but perhaps "Date" would be more descriptive.
- It would be really helpful to have a description of what a flow duration curve is and why it's useful before the code to make the plot. As someone who's not familiar with this kind of plot, I found it difficult to interpret. 
- It would also be helpful to have a sentence describing what exceedence is. I had to google it to try and get a better understanding of the plot, and I'm still not entirely clear about it. 

You've done a really great job! Thanks for all of your hard work on the UI, I think it's a really nice feature!

**Pull request merged**
