### PR TITLE
Added surface area duration curve notebook.

### PR DESCRIPTION
**Pull request by MatthewJA**
### Proposed changes
Added notebook that generates surface area duration curves.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
Nice, thanks @MatthewJA! I'll do a review tomorrow hopefully 👍

**Review by BexDunn — COMMENTED** [review]
Very cool - are you planning on adding this to the index? (README.rst)

**Review by CEKrause — COMMENTED** [review]
Super cool notebook, and really nicely written. I have a couple of small suggestions:
- Include a hyperlink to the DEA Waterbodies notebook or webpage so people can find some context for what DEA Waterbodies is
- Include at the top the hyperlink to the CSVs on S3 - you have this in a cell further down, but it would be good to put this at the top, again for context, and to highlight that this notebook doesn't need to be run on the VDI
- I usually put all the functions that the notebook uses at the top of the notebook near the Config cell, just so that they don't interrupt the flow of the code later on. I think that's a personal preference though, so happy for you to take or leave it. 
- Can you throw in a few extra comments? For a published notebook on dea-notebooks, try to comment pretty much every step. It makes it easier for people to understand what you've done and why, and also to steal bits of code for other things. It doesn't have to be in markdown, you can just comment the lines of code

These are mostly formatting suggestions. The notebook looks great and does really useful analysis.

**Comment by MatthewJA** [comment]
> Very cool - are you planning on adding this to the index? (README.rst)

@BexDunn Is there anything I need to do to add to the index besides specifying the tags at the bottom?

**Comment by BexDunn** [comment]
> > Very cool - are you planning on adding this to the index? (README.rst)
> 
> @BexDunn Is there anything I need to do to add to the index besides specifying the tags at the bottom?

Hey @MatthewJA yup, open up the README.rst file in the same directory and add the filename of your notebook in. This means the restructured text compiler from readthedocs will grab it when it goes through and renders the notebooks :)

**Comment by robbibt** [comment]
Just a big picture/more general question to both @CEKrause as well as @MatthewJA... would it be worth slightly re-framing this notebook to become our official "DEA datasets/DEA Waterbodies.ipynb" notebook that introduces the DEA Waterbodies product?

We could add a bit of extra context up the top that gives an overview of the product (CMI has added a cool new JSON feature that lets you load info directly from the CMI listing to a notebook markdown cell), then the cell demonstrating how to simply load the data from s3, and then the existing surface area duration curve content as kind of a "demo"/application of a particularly useful way to use the data?

Just wanted to raise this as the DEA datasets folder is sadly undeveloped and it would be great to have a nice notebook showing how to use/load all of our products :)

**Comment by MatthewJA** [comment]
@robbibt That sounds like a good idea. Buuuut, if we want a notebook for introducing DEA Waterbodies, I've got a few other potentially more relevant things kicking around. One I have actually displays the waterbody along with its curve and it'd be useful to have a notebook that outputs that plus some basic derived statistics...

**Review by robbibt — CHANGES_REQUESTED** [review]
Hey @MatthewJA , I've just pushed some minor changes to the notebook. It's super cool, and will be a really nice addition to the repo. A few comments/suggestions:

1) I got rid of references to the NCI data as it's on Claire's private branch and I think we should stick to published locations. The data is small and quick to load from s3 so I think we can just go with that for now

2) I've added red text to the notebook in a few locations that would be good to expand on to give a bit more context and explanation to the user. The `Real world example` notebooks are particularly designed to be "problem focused", i.e. outline an important scientific or management problem, and then demonstrate how DEA/satellite data can be used to solve this problem (`Frequently used code` ones are a bit simpler and don't need that bigger context). The main sections that need expansion are the "Background" section at the top, and the two plots down the bottom. @CEKrause and @BexDunn might be able to help out with the "Background"?

3) The functions that are currently included in the notebook are nicely documented and look really useful for future applications, so it might be a good idea to move at least some of them to a DEA Notebooks script. `dea_temporaltools.py` could be a nice place, as it currently contains a single function, or maybe `dea_datahandling.py` which is kind of our catch-all script.

4) `_calculate_sad` and `calculate_sad` might need some extra documentation to differentiate them and explain to a user why we need both (or combine them?). I also think that the `_` variant isn't really the internal variant as it's the one that's actually called by the user - perhaps a different func name would be better.

Happy to help out with any of this, and as soon as things are updated we can merge it in and re-build the user guide so the notebook appears in the official documentation 🚀

**Comment by MatthewJA** [comment]
Thanks @robbibt, will fix and re-request :)

**Comment by robbibt** [comment]
> @robbibt That sounds like a good idea. Buuuut, if we want a notebook for introducing DEA Waterbodies, I've got a few other potentially more relevant things kicking around. One I have actually displays the waterbody along with its curve and it'd be useful to have a notebook that outputs that plus some basic derived statistics...

Forgot to reply to this - yep, sounds good to me, we can make that  notebook quite simple as a basic intro to the product. I might create a draft PR for a DEA dataset notebook that contains the new CMI metadata import code I want to experiment with (which will give a general overview of the DEA Waterbodies product), and later on you can populate it with additional content?

**Comment by MatthewJA** [comment]
@robbibt I've added an explanation of SADC and demonstrated how you could use it to look at different behaviours. :)

**Review by robbibt — APPROVED** [review]
This is fantastic, the updates are really nice and make it a lot more accessible for people who haven't used this kind of analysis before. Thanks @MatthewJA!

**Comment by robbibt** [comment]
Feel free to squash and merge and delete this branch when you're ready

**Pull request merged**
