### PR TITLE
DEA Land Cover  notebook suite

### PR DESCRIPTION
**Pull request by bellemae**
### Proposed changes
A collection of notebooks showing how to access and use the new DEA Land Cover product. 

This contains 4 notebooks and one supplementary scripts file:
- DEA_Land_Cover.ipynb (in DEA_datasets)
- Animated_Land_Cover_plots.ipynb (in Frequently_used_code)
- land_cover_change_mapping.ipynb (in Scientific_workflows/Land_Cover)
- land_cover_pixel_drill.ipynb (in Scientific_workflows/Land_Cover)
- land_cover.py (in Tools/dea_tools)

### Checklist
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by robbibt** [comment]
Hey @bellemae, @margaretharrison, @Kooie-cate, this is incredible! Can't express how excited I am to get this content into the repo - I think it will be hugely useful for helping new users get started quickly with the data. Some feedback for each notebook below - they don't need many changes at all, and most of the stuff below is just minor consistency stuff and some ideas for future additions. I've also made some minor edits to the notebooks and scripts themselves (mainly PEP8/style guide stuff).

---
**Introduction to DEA Land Cover**
This is such a great introductory notebook - does a fantastic job of introducing the main features of the data and how to load/visualise it. Amazing! Only the tiniest bit of feedback:

- `Land cover is the observed physical cover on the Earth's surface` - any way we can use a definition of land cover that doesn't include the word "cover"? Same thing in the following notebooks

---
**Plotting animations of land cover** 

- I love the stacked plot + animation! The only thing that's missing (as noted in the notebook) is being able to have a colour bar as well as the stacked plot, which does make the colours a little harder to interpret. No need to do it for this PR, but in the future a nice compromise could be to use the stacked plot itself as a legend by plotting some data labels on the right hand side (I have DEA Coastlines code to do this). That way the animations would be self-describing to anyone who isn't familiar with the colour scheme. E.g. something like this:

image
(the labels would jump around and update for each frame in the animation; you might need to only show the labels where a class is e.g. > 5% of the total in a given year so they don't overlap)

- Could the `Why is my animation producing an error or plotting no data?` section be removed if we had a slightly more detailed error message? Deliberately raising an error inside the notebook currently causes the notebook to bail before the end, and might eventually cause further issues if we expand our automated tests to cover this notebook. E.g. perhaps wording like this might make it clearer:

> "Could not automatically determine colour scheme from array name 'ntv_only'. Please change the name of the array using `da.rename(...)` to match one of the following options: 'level3', 'level3_change_colour_scheme', 'level3_change_colour_bar', 'lifeform_veg_cat_l4a', 'canopyco_veg_cat_l4d', 'waterstt_wat_cat_l4a', 'watersea_veg_cat_l4a_au', 'inttidal_wat_cat_l4a', 'waterper_wat_cat_l4d_au', 'baregrad_phy_cat_l4d_au', 'level4', or 'level4_colourbar_labels'. Alternatively, use the 'layer' parameter in `lc_animation` to manually specify the layer colour scheme: `lc_animation(..., layer='level3', ...)`."

(not sure whether the best place for this would be in the underlying `lc_colourmap` func, or by catching the assertion error using try/except and providing the more explanatory one instead inside `lc_animation`)

---
**DEA Land Cover pixel drill**
**DEA Land Cover change mapping**

- Both super nice - particularly love the "land cover history" plots! Biggest comment here: I think they might be too nice to resign to the "Scientific workflows" folder. That folder is in some ways is where more complex experimental code goes to die (it's not event synced to the DEA Sandbox or the User Guide because we don't promise that any of the code in there will work). I think both notebooks would be better placed in `Frequently_used_code` (in their current state), or even `Real_world_examples` if you wanted to add a little bit more of an imaginary case study flavour to them (e.g. how the pixel drill or land cover change maps could be used to answer a real-world problem).

If you do decide to promote these to one of those folders, they might need some minor tweaks to match the format of the other notebooks (changing file names from lower case to sentence case, removing the "1.", "2." etc in the pixel drill headers).

---
**land_cover.py**
Any chance we could rename this to `landcover.py`? (It's the only one there that uses the underscore at the moment, and it'd be nice to keep things consistent)

**Review by BexDunn — APPROVED** [review]
I really like the DEA_Land_Cover.ipynb notebook, it's wonderful particularly the class explanations at the bottom. I like all the cross-linkages to other notebooks and info, it's very useable and also pretty.

I agree with Robbi's comments in general, and agree with the suggested filerenaming for landcover.py and the Scientific Workflows notebooks. 

I really like the Animation Notebook, also the trick where you get to change the animation so that it works! Love it

I think the Scientific Workflow notebooks are too good and need to go into Frequently used code!

Well done, these are brilliant. I couldn't find anything that needed fixing other than adding one word in one notebook, and agreeing with Robbi's comments. Everything is intuitive and has heaps of context, and the functions are all well documented and easy to understand. These are really very cool and good. 

Oh, I should point out that I disagree with @robbibt on removing the `why is my animation producing an error or plotting no data?` section, I think it's a great interactive bit for new folks to feel involved/ literal stakeholder engagement! And that I am not sure we can run tests on the interactive notebooks at this stage anyway so I think it's an arguable point either way!

**Comment by pjt554** [comment]
In Notebook Animations_Land_Cover_plots.ipynb, the program halted in Cell 10, with following error message:
"---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_201/820435371.py in <module>
     15 
     16 # Generate plot
---> 17 lc_animation(xr_veg, file_name=file_name, colour_bar=True)

~/dev/dea-notebooks/Tools/dea_tools/land_cover.py in lc_animation(da, file_name, layer, stacked_plot, colour_bar, animation_interval, width_pixels, dpi, font_size, label_ax)
    530 
    531     # Create colour map and normalisation for specified lc layer
--> 532     layer_cmap, layer_norm, cb_labels, cb_ticks = lc_colourmap(
    533         layer, colour_bar=True)
    534 

~/dev/dea-notebooks/Tools/dea_tools/land_cover.py in lc_colourmap(colour_scheme, colour_bar)
    331     colour_scheme = colour_scheme.lower()
    332     # Ensure a valid colour scheme was requested
--> 333     assert (colour_scheme in lc_colours.keys(
    334     )), f'colour scheme must be one of [{lc_colours.keys()}] (got "{colour_scheme}")'
    335 

AssertionError: colour scheme must be one of [dict_keys(['level3', 'level3_change_colour_scheme', 'level3_change_colour_bar', 'lifeform_veg_cat_l4a', 'canopyco_veg_cat_l4d', 'waterstt_wat_cat_l4a', 'watersea_veg_cat_l4a_au', 'inttidal_wat_cat_l4a', 'waterper_wat_cat_l4d_au', 'baregrad_phy_cat_l4d_au', 'level4', 'level4_colourbar_labels'])] (got "ntv_only")"

To fix the error, you can change the name of the xarray.DataArray to "level3".

Alternatively, you can use the layer setting to specify the layer. The below example demonstrates how to use the layer argument.

**Comment by bellemae** [comment]
@robbibt @BexDunn @pjt554 I think we've now addressed all items raised. 
- moved and renamed notebooks
- renamed .py file to remove _
- reworded land cover definition
- removed error example in animation notebook and replaced with helpful error message.
* note, will leave the additional labels on the stacked plot for a feature enhancement

**Review by robbibt — APPROVED** [review]
Made some final very minor updates (updated the readme to point to the new notebook names, fixed links to Frequently_used_notebooks in the DEA_Land_Cover notebook, fixed broken DEA header images in some of the notebooks) - everything looks fantastic and I think ready to merge!

(just make sure to select the "Squash and Merge" option when merging - there's a lot of commits!)

**Pull request merged**
