### PR TITLE
Added elevation notebook

### PR DESCRIPTION
**Pull request by MatthewJA**
A demo of estimating elevations using WOfS.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by CEKrause** [comment]
- `stations_in_range` - does 'range' mean 'bounding box'? I couldn't spot a buffer, so I assume you're just looking for stream gauges within the specific bounding box? Could you please clarify this?
- is the `get_stream_data` function here the same as the one in the Scripts/BoM file? If so, can you just import that one? If not can you please add a sentence or two describing what you're doing here that's different?
- 'find the first shared observation' - shared with what?
- 'Mask the data to only include wet or not wet, and set everything else to nan.' - just checking there aren't more bit flags to include, like low solar angle etc? Ness had a list of a few she was using for waterbodies. Possibly for this application you want to err on the side of confidence though and exclude those other flags?
- 'Plot WOfS against stream gauge' - can you please add axis labels to the plot with the 0 and 128? I am not entirely sure what the plot is showing.
- 'We can then visualise this as a heightmap:' holy crap! This is amazing!!!!!!!!
- 'depth map' - I am not sure what you mean by 'Depth from maximum WOfS extent (m)'. You mean depth of water if the maximum amount of area is observed as wet? Can you convert to depth relative to the stream channel? So zero would be the top of the channel, and the floodplain would then be positive, and the stream negative? It may be too complicated?
- 'We can then apply the calibration to the WOfS summary:' - can you please add a label to the colourbar for the red/blue plot in this section? What is the anomaly?

Also, this notebook is absolutely nuts!!!! Well done.

**Comment by MatthewJA** [comment]
image
Added a little widget to help investigate parts of the correlation plot.

**Comment by MatthewJA** [comment]
> stations_in_range - does 'range' mean 'bounding box'? I couldn't spot a buffer, so I assume you're just looking for stream gauges within the specific bounding box? Could you please clarify this?

Made it explicit that it's a bbox.

> is the get_stream_data function here the same as the one in the Scripts/BoM file? If so, can you just import that one? If not can you please add a sentence or two describing what you're doing here that's different?

A bit different. I've added a sentence explaining that.

> 'find the first shared observation' - shared with what?

Clarified.

> 'Mask the data to only include wet or not wet, and set everything else to nan.' - just checking there aren't more bit flags to include, like low solar angle etc? Ness had a list of a few she was using for waterbodies. Possibly for this application you want to err on the side of confidence though and exclude those other flags?

There are more flags, but as you've said, let's err on the side of confidence.

> 'Plot WOfS against stream gauge' - can you please add axis labels to the plot with the 0 and 128? I am not entirely sure what the plot is showing.

Yep, done.

> 'We can then visualise this as a heightmap:' holy crap! This is amazing!!!!!!!!

:D Thank you!

> 'depth map' - I am not sure what you mean by 'Depth from maximum WOfS extent (m)'. You mean depth of water if the maximum amount of area is observed as wet? Can you convert to depth relative to the stream channel? So zero would be the top of the channel, and the floodplain would then be positive, and the stream negative? It may be too complicated?

Deleted this plot, since it's not that useful IMO. It's hard to estimate the top of the channel since it's not clearly defined, so I haven't done that conversion.

> 'We can then apply the calibration to the WOfS summary:' - can you please add a label to the colourbar for the red/blue plot in this section? What is the anomaly?

I can't seem to find the docs for colourbar labels for xarray plots... but really this plot is just kind of confusing, so I've deleted it.

> Also, this notebook is absolutely nuts!!!! Well done.

Thank you! :)

**Comment by CEKrause** [comment]
Looks amazing! Is there a trick for getting your widgets to save their state? All your awesome plots are missing from the notebook output cells now that you've made them a widget. Otherwise, this one is good to go.

**Comment by MatthewJA** [comment]
I think I can do something like that, I'll investigate!

**Comment by MatthewJA** [comment]
@CEKrause I've added most of the plots back in by forcing the GUI back into inline mode :) the interactive plot won't show up still, but that's not a huge loss (it's more fun to poke around anyway)

**Review by CEKrause — APPROVED** [review]
Looks excellent!

**Pull request merged**
