### PR TITLE
Draft of Near Real-time Burnt Area Mapping DEA notebook for review

### PR DESCRIPTION
**Pull request by Matt-dea**
### Proposed changes
New notebook.

### Concerns
Kernel crashes when user requests a large AOI and a large number of images are extracted. Mostly occurs in the Baseline load_ard extract. Not sure if I can use Dask to solve as I need to visualise the images in the following plot.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)

### CODE REVIEW

**Comment by robbibt** [comment]
Hey @Matt-dea and @erin-telfer - will get on this first thing next week, sorry for the delay!

**Comment by geoscience-aman** [comment]
<p>To clarify, when I said "where you are running it", I mean how much memory your sandbox environment has.</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1018/discussion/#comment-1495391989'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Matt-dea** [comment]
<p>Yep I agree :)</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1018/discussion/#comment-1495391958'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Matt-dea** [comment]
<p>Although i noticed that some of the other examples are a bit mixed haha, I will keep DEA capitalised </p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1018/discussion/#comment-1495391958'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Matt-dea** [comment]
<ol><li>Instead of linking to examples, I have toned down this section. Erin will probably review further. Thanks!</li><li>Excellent point. I have added this point, and replaced the text with the standard DEA NRT blurb.</li><li>Sounds good, I have imlpemented for all algorithms.</li><li>Updated. Thanks!</li></ol><p> </p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1018/discussion/#comment-1495391969'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Matt-dea** [comment]
<p>Thats weird, the dot points appear on their own line for me? I will have to look into this further!</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1018/discussion/#comment-1495391981'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Matt-dea** [comment]
<p>As for the links, I agree that is a good idea but see that it is not done in the other notebooks. I will not implement just to make things consistent :)</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1018/discussion/#comment-1495391981'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by robbibt — CHANGES_REQUESTED** [review]
Hey @Matt-dea, this is awesome work! The notebook is great: nicely documented and clean code, and the outputs are fantastic! I've put a bunch of feedback below - it's all minor stuff, and the notebook is already very close to being ready to publish!

1. This is a tricky one since the notebook is primarily focused on NRT analysis... but the biggest issue I had was that the use of `datetime.today().strftime("%Y-%m-%d")` to set `nrt_date_end` meant that when I re-ran it today on April 19 , the notebook produced no fire polygon results because there wasn't a fire during the analysis period. I think this will be confusing to users as they'll end up with an empty result and wonder if it was something they did wrong... it will probably be better to hard-code `nrt_date_end` to a specific date that we know includes a nice fire, e.g. `nrt_date_end = "2023-03-31"`, but then provide really clear instructions to set this to `nrt_date_end = datetime.today().strftime("%Y-%m-%d")` for today's date.

2. I'd rename `Near_Realtime_Burnt_Area_Mapping.ipynb` to `Burnt_area_mapping_near_real_time.ipynb`. That way it will appear side-by-side with the existing notebook and be easier to find.

3. For the "safety of life decisions" warning, we could consider using an actual alert box like this - I think we could make more of these kind of boxes across DEA Notebooks, they're great for catching attention:
```
<div class="alert alert-block alert-danger"> <b>IMPORTANT</b>: This notebook and the datasets visualised and produced are not to be used for safety of life decisions. For local updates and alerts, please refer to your state emergency or fire service. </div>
```
image

4. Change "Sentinel 2a" and "Sentinel 2b" in the intro to "Sentinel-2A" and "Sentinel-2B"

5. Rather than using bold in the "Description" contents list, another option could be to hyperlink them instead as we've recently started doing in recent notebooks (although we need to update the template notebook) - each heading has a "#Blah" format anchor link that you can copy from the URL bar if you click on them: e.g.: `1. [Getting Started and Defining an AOI](#1.-Getting-started-and-defining-an-AOI)`
image

5. This section says the default is -1 but the code says 1:
```
# Index selection for the Near Real-time image chosen above. The default value of -1 selects the most recent image regardless of suitability.
nrt_img_index = 1
```
6. A completely option one: a lot of the notebook is taken up with plotting code - potentially some of this could be simplified by creating a reproducible function that handles the plotting (it could live in `dea_tools.plotting`), and then re-use that throughout the notebook. The tricky thing would be some of the cells that combine both Landsat and S2 data, but you could probably just run that function seperately on both sources of data rather than having them on the same plot. 😃

**Comment by robbibt** [comment]
Ah, two more related things:

- I added our pull review checklist back into your PR above - it's worth running through those items one by one to make sure they're all ticked off! For some of the NCI-related ones, I'm happy to quickly duck into the NCI to check it runs there if you don't have an account - otherwise you can mark the notebook as only compatible with the Sandbox instead. 
image
- One thing that's unfortunately not mentioned in the checklist (#1040) is that we need to add the notebook to the `Real_world_examples` readme in order for it to appear in the DEA User Guide docs - once you've renamed it, you can add it here:
https://github.com/GeoscienceAustralia/dea-notebooks/blob/matt.e/Real_world_examples/README.rst

**Comment by Matt-dea** [comment]
<p>Great point, I have added a disclaimer for large AOI's with a suggestion to reduce the AOI or increase the min_gooddata values if a crash occurs.</p>

---

 <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1018/discussion/#comment-1495391989'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Matt-dea** [comment]
Closing PR. New PR initiated due to complicated conflicts with develop.
All change requested above implemented.

**Pull request closed without merging**
