### PR TITLE
Intro to plotting

### PR DESCRIPTION
**Pull request by erialC-P**
_Note: checklist below only relevant if committing to the [`develop`](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop) branch:_

### Proposed changes
This is a placeholder notebook for the new Beginners_guide

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [x] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [x] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with

### CODE REVIEW

**Comment by erialC-P** [comment]
Feel free to add to it but if not, I will continue working on it once back from leave next week.

**Comment by robbibt** [comment]
@erialC-P I just did a quick tidy of the branch to remove all new notebooks except the one that's specific to the pull request (this will reduce the likelihood of merge conflicts in the future).

Before you do any more work, please check out this branch and run `git pull` to get the latest version!

**Comment by erialC-P** [comment]
Users finally get to see some imagery here using scripts from deaplotting.py
To see where this notebook is designed to sit within the Beginners Guide folder, please see:
https://github.com/GeoscienceAustralia/dea-notebooks/wiki/DEA-notebooks-refresh:-notebook-allocations

**Comment by erialC-P** [comment]
I really like the revisions you've both made @robbibt and @caitlinadams 
This is going to become another of my go-to guides. Thanks for your comments!!
I have made some minor edits and changed the wording slightly around clipping the data to improve the colour stretch. You might want to review those changes quickly but otherwise I think this notebook is ready to go! :D

**Pull request merged**
