### PR TITLE
Sentinel 2 waterbodies notebook

### PR DESCRIPTION
**Pull request by MatthewJA**
Here's a notebook that generates polygons with Sentinel 2 MNDWI, Landsat 8 MNDWI, and WOfS, and compares their time series.

I haven't a) run it in sequential order, or b) run it on the NCI, because it takes ages to run and I want to make sure it's feature complete first.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex.html), and re-use tags if possible)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)

### CODE REVIEW

**Review by robbibt — CHANGES_REQUESTED** [review]
Hey @MatthewJA , another super cool notebook. I have some overall comments below - I think the main things that need to be fixed up are improving code and markdown documentation and perhaps thinking about ways to simplify the notebook (e.g. removing any sections which aren't absolutely critical to the overall analysis). 

- If the notebook takes a while to load (more than a few minutes), it would be good to focus on a smaller example area (e.g. a single waterbody). That way it can serve as a nice quick to run demo, but still allow users who want to analyse a larger area to modify the extent and re-run.
- Some sections need additional markdown explanation and code comments to walk the user through what each piece of the analysis is doing. In particular, "Build a virtual product for the MNDWI calculation" (as many users will not have loaded data using virtual products before) and "Surface area time series calibration", "Generating time series", "Comparing time series" (anywhere there's more than a line or two of code, or functions without docstrings... ideally we want reasonably inexperienced users to be able to follow every step of the analysis, or at least appreciate why it's being done).
- The "cliquing" section should have some additional explanation aimed at explaining what this does and why it is useful for users who have never used this. Same for the graph at cell 28; some extra explanation on how to interpret the graph aimed at new users would be great.
- The "What do the time series look like?" is currently very long. I would choose a single example graph rather than a large sequence or a handful of contrasting results that can fit inside an single figure, and then explain just those in more detail.
- We are currently avoiding custom pip installs in these example notebooks as they reduce reproducibility and lead to downstream issues where users come to us complaining about issues based on a customised environment, which makes it difficult to bug fix. Is it possible to replace the functionality in `pip install rioxarray disjoint-set` with functionality from existing packages? Otherwise we can try and get the new package installed, although for `rioxarray` it might be a bit tricky as that package has a large amount of overlap with `datacube` itself...
- Would a conclusions section here be useful? There's a lot of different things going on, and it might be nice to wrap things up neatly at the end.

Minor updates:
- Weird formatting on the square metre units here - does this use markdown formatting or something else?
image
- Move "analysis parameters" below "Connect to the datacube", and ensure all sections follow order in template notebook
- Split `:
bbox = xlim, ylim = ((143.70774, 143.89147), (-35.71674, -35.48853))  # Kerang Wetlands` into two lines to match other notebooks and drop `bbox =` if it's not being used
- Update `dc = datacube.Datacube(app="Sentinel2Waterbodies")` to `dc = datacube.Datacube(app="Sentinel_2_Waterbodies")` to match notebook title
- Change to direct link: "MNDWI (DOI:10.1080/01431160600589179)"
- Can `mask_to_polygons` be replaced with the existing `xr_polygonise` function? 
- Can we replace the `%%bash` block with loading the Waterbodies data directly using `pandas`? This would reduce the amount of new techniques users need to learn, and bring it in line with the existing approach in `Surface_water_duration.ipynb`.

**Comment by robbibt** [comment]
The virtual product is super cool by the way. I think it probably works fine in-text here for now, but in time we should think about moving it out to a separate YAML, as per #640

**Comment by MatthewJA** [comment]
Thanks for the feedback @CEKrause and @robbibt. Super helpful for getting this notebook to where I want to get it. I'll work on it and get back to y'all.

**Comment by MatthewJA** [comment]
Thanks again, super helpful. I've stripped it down and I think it makes a bit more sense now, and I've tidied up the bits requested.

I did have an issue with Dask where it was _ridiculously_ slow without preloading, so could someone please take a look at my Dask code to see what I'm doing wrong? (If anything, I guess. Preloading seems to fix it just fine)

**Review by robbibt — APPROVED** [review]
Have pushed some updates below, mainly to add some extra code documentation and to reduce the time period further to reduce the load time. The dask issue is annoying, but we can resolve this outside this PR

**Pull request merged**
